/** One selectable option on a practice question. */
export type PracticeQuestionOption = {
  id: string
  text: string
}

/** One multiple-choice practice question generated by the AI tutor. */
export type PracticeQuestion = {
  id: string
  question: string
  options: Array<PracticeQuestionOption>
  correctOptionId: string
  explanation?: string
}

/** Structured payload produced by the `generatePracticeQuestions` tool call. */
export type PracticeQuestionsPayload = {
  topic?: string
  questions: Array<PracticeQuestion>
  /**
   * Stamped by {@link namespacePracticeQuestions} once per generation so that
   * asking for "more questions" later in the same chat can't collide with an
   * earlier quiz's question/option ids. Absent on the raw tool-call output.
   */
  quizId?: string
  /** Submitted answers (question id -> chosen option id), set on submit. */
  answers?: Record<string, string>
}

/**
 * Defensively parses an untrusted value (tool output, SSE frame, or a JSON
 * column read back from the DB) into a {@link PracticeQuestionsPayload}.
 * Drops individual questions/options that don't match the shape rather than
 * rejecting the whole payload, mirroring `parseChatHistory`'s leniency.
 */
export function parsePracticeQuestionsPayload(
  value: unknown,
): PracticeQuestionsPayload | null {
  if (!value || typeof value !== 'object') return null
  const record = value as Record<string, unknown>
  if (!Array.isArray(record.questions)) return null

  const questions = record.questions.flatMap(
    (entry): Array<PracticeQuestion> => {
      if (!entry || typeof entry !== 'object') return []
      const row = entry as Record<string, unknown>
      if (typeof row.id !== 'string' || typeof row.question !== 'string')
        return []
      if (!Array.isArray(row.options)) return []

      const options = row.options.flatMap(
        (option): Array<PracticeQuestionOption> => {
          if (!option || typeof option !== 'object') return []
          const optionRow = option as Record<string, unknown>
          if (
            typeof optionRow.id !== 'string' ||
            typeof optionRow.text !== 'string'
          ) {
            return []
          }
          return [{ id: optionRow.id, text: optionRow.text }]
        },
      )

      if (options.length < 2) return []
      if (
        typeof row.correctOptionId !== 'string' ||
        !options.some((option) => option.id === row.correctOptionId)
      ) {
        return []
      }

      return [
        {
          id: row.id,
          question: row.question,
          options,
          correctOptionId: row.correctOptionId,
          explanation:
            typeof row.explanation === 'string' ? row.explanation : undefined,
        },
      ]
    },
  )

  if (questions.length === 0) return null

  return {
    topic: typeof record.topic === 'string' ? record.topic : undefined,
    questions,
    quizId: typeof record.quizId === 'string' ? record.quizId : undefined,
    answers: parseAnswersRecord(record.answers),
  }
}

function parseAnswersRecord(
  value: unknown,
): Record<string, string> | undefined {
  if (!value || typeof value !== 'object' || Array.isArray(value))
    return undefined
  const entries = Object.entries(value as Record<string, unknown>).filter(
    (entry): entry is [string, string] => typeof entry[1] === 'string',
  )
  return entries.length > 0 ? Object.fromEntries(entries) : undefined
}

/**
 * Namespaces every question/option id under `quizId` so that generating
 * "more questions" in the same chat never reuses an earlier quiz's ids —
 * the model has no memory of ids it already used in this conversation.
 */
export function namespacePracticeQuestions(
  payload: PracticeQuestionsPayload,
  quizId: string,
): PracticeQuestionsPayload {
  return {
    ...payload,
    quizId,
    questions: payload.questions.map((question) => {
      const questionId = `${quizId}-${question.id}`
      const optionIdByOriginalId = new Map(
        question.options.map((option) => [
          option.id,
          `${questionId}-${option.id}`,
        ]),
      )
      return {
        ...question,
        id: questionId,
        options: question.options.map((option) => ({
          ...option,
          id: optionIdByOriginalId.get(option.id) ?? option.id,
        })),
        correctOptionId:
          optionIdByOriginalId.get(question.correctOptionId) ??
          question.correctOptionId,
      }
    }),
  }
}

/** Compact plain-text rendition used to keep the model's own history coherent. */
export function formatPracticeQuestionsForContext(
  payload: PracticeQuestionsPayload,
): string {
  const lines = payload.questions.map((question, index) => {
    const correctText =
      question.options.find((option) => option.id === question.correctOptionId)
        ?.text ?? question.correctOptionId
    return `${index + 1}. ${question.question} (Correct: ${correctText})`
  })

  const heading = payload.topic
    ? `[Generated practice questions on ${payload.topic}]`
    : '[Generated practice questions]'

  return `${heading}\n${lines.join('\n')}`
}
