import type {
  InterviewDomain,
  InterviewTopic,
} from '@/server/api/interviews/types/interviewSession'

/** Catalog storage shape — `domain` is the record key, not repeated per topic. */
export type CatalogTopic = Omit<InterviewTopic, 'domain'>

const INTERVIEW_TOPIC_CATALOG: Record<InterviewDomain, Array<CatalogTopic>> = {
  frontend: [
    {
      id: 'frontend-html',
      label: 'HTML',
      iconKey: 'layout-template',
      blurb:
        'Semantic HTML5, document structure (head body), and forms & input types.',
      rubricFocus: [
        'Semantic HTML5',
        'Document structure',
        'Forms & input types',
        'Labels & buttons',
      ],
      subtopics: [
        'Semantic HTML5',
        'Document structure (head body)',
        'Forms & input types',
        'Labels & buttons',
        'Tables & lists',
        'Images & media (img video audio)',
        'Accessibility basics (labels ARIA)',
        'SEO-friendly markup',
        'Cross-browser compatible pages',
      ],
    },
    {
      id: 'frontend-css',
      label: 'CSS',
      iconKey: 'palette',
      blurb:
        'Selectors (element class id), box model (margin padding border), and colors & typography.',
      rubricFocus: [
        'Selectors',
        'Box model',
        'Colors & typography',
        'Backgrounds & borders',
      ],
      subtopics: [
        'Selectors (element class id)',
        'Box model (margin padding border)',
        'Colors & typography',
        'Backgrounds & borders',
        'Display & positioning',
        'Units (px rem % vh vw)',
        'Pseudo-classes & pseudo-elements',
        'Flexbox (direction align justify wrap)',
        'CSS Grid (rows columns areas gaps)',
        'Responsive layouts & media queries',
        'Mobile-first design',
        'Common layouts (header sidebar footer)',
        'CSS frameworks awareness (Bootstrap or Tailwind)',
      ],
    },
    {
      id: 'frontend-javascript',
      label: 'JavaScript',
      iconKey: 'code',
      blurb:
        'Variables (let const var), data types, and type coercion & equality (== vs ===).',
      rubricFocus: [
        'Variables',
        'Data types',
        'Type coercion & equality',
        'Operators',
      ],
      subtopics: [
        'Variables (let const var)',
        'Data types',
        'Type coercion & equality (== vs ===)',
        'Operators',
        'Conditionals (if else switch)',
        'Loops (for while for...of)',
        'Strings arrays objects',
        'Functions (declarations expressions arrow)',
        'Parameters return values & default parameters',
        'Scope (global function block) & closures basics',
        'Hoisting intuition',
        'Template literals',
        'Destructuring',
        'Spread & rest',
        'Array methods (map filter reduce forEach find)',
        'Optional chaining & nullish coalescing',
        'Modules (import export)',
        'DOM tree & selectors (getElementById querySelector querySelectorAll)',
        'Reading updating content',
        'createElement append remove',
        'ClassList & inline styles',
        'Event listeners (click input submit)',
        'Event bubbling & delegation',
        'Form validation',
        'Sync vs async',
        'Callbacks',
        'Promises (then catch finally)',
        'Async/await',
        'Fetch API (GET POST)',
        'JSON parsing',
        'Error handling for network calls',
      ],
    },
    {
      id: 'frontend-how-the-web-works',
      label: 'How the Web Works',
      iconKey: 'network',
      blurb:
        'Client-server model, HTTP methods & status codes, and request-response cycle.',
      rubricFocus: [
        'Client-server model',
        'HTTP methods & status codes',
        'Request-response cycle',
        'Headers cookies sessions',
      ],
      subtopics: [
        'Client-server model',
        'HTTP methods & status codes',
        'Request-response cycle',
        'Headers cookies sessions',
        'CORS basics',
        'REST API consumption from browser',
        'Browser DevTools debugging',
      ],
    },
    {
      id: 'frontend-react',
      label: 'React',
      iconKey: 'atom',
      blurb:
        'JSX & functional components, props vs state, and controlled vs uncontrolled components.',
      rubricFocus: [
        'JSX & functional components',
        'Props vs state',
        'Controlled vs uncontrolled components',
        'useState & useEffect',
      ],
      subtopics: [
        'JSX & functional components',
        'Props vs state',
        'Controlled vs uncontrolled components',
        'useState & useEffect',
        'useEffect dependency pitfalls',
        'Conditional rendering',
        'Lists keys & list-rendering bugs',
        'Controlled forms',
        'Component composition & reusability',
        'Virtual DOM & reconciliation intuition',
        'Component re-render intuition',
        'Lifting state up',
        'Custom hooks basics',
        'React Router (routes navigation)',
        'Context API basics',
        'Fetching data in React (loading error empty states)',
        'localStorage with React',
        'Reusable UI / container-presentational patterns',
        'Building CRUD UI from scratch',
      ],
    },
    {
      id: 'frontend-git-github',
      label: 'Git & GitHub',
      iconKey: 'git-branch',
      blurb:
        'git init add commit status log, clone push pull, and branching & merging.',
      rubricFocus: [
        'git init add commit status log',
        'Clone push pull',
        'Branching & merging',
        'Pull requests & code review basics',
      ],
      subtopics: [
        'git init add commit status log',
        'Clone push pull',
        'Branching & merging',
        'Pull requests & code review basics',
        'Reading diffs',
        'Merge conflicts intro',
        '.gitignore',
        'Repository hygiene & clean commit history',
      ],
    },
    {
      id: 'frontend-dev-tooling',
      label: 'Developer Tooling',
      iconKey: 'wrench',
      blurb:
        'VS Code & terminal workflow, browser DevTools, and postman / API clients.',
      rubricFocus: [
        'VS Code & terminal workflow',
        'Browser DevTools',
        'Postman / API clients',
        'Package managers',
      ],
      subtopics: [
        'VS Code & terminal workflow',
        'Browser DevTools',
        'Postman / API clients',
        'Package managers (npm pip)',
        'Reading docs & debugging mindset',
      ],
    },
  ],
  backend: [
    {
      id: 'backend-python',
      label: 'Python',
      iconKey: 'terminal',
      blurb: 'Variables & data types, operators, and conditionals.',
      rubricFocus: [
        'Variables & data types',
        'Operators',
        'Conditionals',
        'Loops',
      ],
      subtopics: [
        'Variables & data types',
        'Operators',
        'Conditionals',
        'Loops (for while break continue)',
        'Functions (params return default args scope)',
        'Input/output (input print)',
        'OOP basics (classes objects)',
        'Exception handling',
        'Strings lists tuples dictionaries sets',
        'Indexing slicing & collection methods',
        'Built-in functions (len sorted min max sum)',
        'Nested structures',
        'JSON handling',
        'File I/O',
        'Type hints awareness',
        'Virtual environments (venv)',
        'pip & requirements.txt',
        'Modules packages & project structure',
        'Debugging locally',
      ],
    },
    {
      id: 'backend-dsa',
      label: 'Data Structures & Algorithms',
      iconKey: 'sigma',
      blurb: 'Big-O time & space intuition, linear search, and binary search.',
      rubricFocus: [
        'Big-O time & space intuition',
        'Linear search',
        'Binary search',
        'Bubble sort',
      ],
      subtopics: [
        'Big-O time & space intuition',
        'Linear search',
        'Binary search',
        'Bubble sort',
        'Selection sort',
        'Problem decomposition',
        'Nested loops & complexity patterns',
        'Solving structured coding problems with lists strings dicts',
      ],
    },
    {
      id: 'backend-http-rest-apis',
      label: 'HTTP & REST APIs',
      iconKey: 'network',
      blurb:
        'Client-server architecture, HTTP methods (GET POST PUT PATCH DELETE), and status codes & status-code selection.',
      rubricFocus: [
        'Client-server architecture',
        'HTTP methods',
        'Status codes & status-code selection',
        'Headers & body',
      ],
      subtopics: [
        'Client-server architecture',
        'HTTP methods (GET POST PUT PATCH DELETE)',
        'Status codes & status-code selection',
        'Headers & body',
        'REST resources & endpoints',
        'API contracts (request response errors)',
        'Pagination filtering sorting',
        'Idempotency & safe methods intuition',
        'REST design trade-offs',
        'Testing APIs with Postman or Swagger',
        'Debugging failing endpoints',
      ],
    },
    {
      id: 'backend-fastapi',
      label: 'FastAPI',
      iconKey: 'code',
      blurb:
        'Project setup & first endpoints, path & query parameters, and request body & response models.',
      rubricFocus: [
        'Project setup & first endpoints',
        'Path & query parameters',
        'Request body & response models',
        'Full CRUD APIs',
      ],
      subtopics: [
        'Project setup & first endpoints',
        'Path & query parameters',
        'Request body & response models',
        'Full CRUD APIs',
        'Pydantic schemas & validation',
        'Dependency injection',
        'Middleware',
        'CORS configuration',
        'Background tasks',
        'File upload/download',
        'Environment variables & config',
        'OpenAPI / Swagger UI',
        'Async awareness (async await)',
        'Integrating third-party APIs',
      ],
    },
    {
      id: 'backend-sql',
      label: 'SQL',
      iconKey: 'database',
      blurb:
        'Relational DB concepts, CREATE TABLE & data types, and INSERT SELECT UPDATE DELETE.',
      rubricFocus: [
        'Relational DB concepts',
        'CREATE TABLE & data types',
        'INSERT SELECT UPDATE DELETE',
        'WHERE ORDER BY LIMIT',
      ],
      subtopics: [
        'Relational DB concepts',
        'CREATE TABLE & data types',
        'INSERT SELECT UPDATE DELETE',
        'WHERE ORDER BY LIMIT',
        'Primary & foreign keys',
        'Relationships (1:1 1:N N:M)',
        'INNER JOIN & LEFT JOIN',
        'Aggregates (COUNT SUM AVG MIN MAX)',
        'GROUP BY & HAVING',
        'Subqueries basics',
        'Indexes intuition',
        'PostgreSQL/MySQL familiarity',
        'SQL vs NoSQL when to use',
        'Writing interview-style SQL queries',
      ],
    },
    {
      id: 'backend-orm-sqlalchemy',
      label: 'ORM (SQLAlchemy)',
      iconKey: 'database',
      blurb: 'ORM vs raw SQL, models & sessions, and CRUD with ORM.',
      rubricFocus: [
        'ORM vs raw SQL',
        'Models & sessions',
        'CRUD with ORM',
        'One-to-many relationships',
      ],
      subtopics: [
        'ORM vs raw SQL',
        'Models & sessions',
        'CRUD with ORM',
        'One-to-many relationships',
        'Filtering & joins via ORM',
        'Integrating ORM with FastAPI',
        'N+1 query problem intuition',
        'Migrations awareness (Alembic basics)',
      ],
    },
    {
      id: 'backend-auth-api-security',
      label: 'Auth & API Security',
      iconKey: 'shield-check',
      blurb:
        'Password hashing intuition, JWT / token auth basics, and protected routes.',
      rubricFocus: [
        'Password hashing intuition',
        'JWT / token auth basics',
        'Protected routes',
        'OAuth2 awareness',
      ],
      subtopics: [
        'Password hashing intuition',
        'JWT / token auth basics',
        'Protected routes',
        'OAuth2 awareness',
        'Input validation & sanitization',
        'Common API security mistakes',
        'Secrets & .env management',
      ],
    },
    {
      id: 'backend-genai-llm-apis',
      label: 'GenAI & LLM APIs',
      iconKey: 'sparkle',
      blurb:
        'LLM fundamentals, prompt engineering (system prompts chains), and structured outputs (JSON).',
      rubricFocus: [
        'LLM fundamentals',
        'Prompt engineering',
        'Structured outputs',
        'Calling OpenAI Anthropic or similar APIs from FastAPI',
      ],
      subtopics: [
        'LLM fundamentals',
        'Prompt engineering (system prompts chains)',
        'Structured outputs (JSON)',
        'Calling OpenAI Anthropic or similar APIs from FastAPI',
        'Auth rate limits & token cost awareness',
        'Streaming responses basics',
        'Embeddings overview',
        'RAG basics (retrieve then generate)',
        'Wiring LLM features into FastAPI services',
      ],
    },
    {
      id: 'backend-hld-lld-basics',
      label: 'HLD / LLD Basics',
      iconKey: 'network',
      blurb:
        'HLD vs LLD difference, drawing high-level architecture (client API DB), and monolith vs microservices intuition.',
      rubricFocus: [
        'HLD vs LLD difference',
        'Drawing high-level architecture',
        'Monolith vs microservices intuition',
        'Caching & scaling basics',
      ],
      subtopics: [
        'HLD vs LLD difference',
        'Drawing high-level architecture (client API DB)',
        'Monolith vs microservices intuition',
        'Caching & scaling basics',
        'Database choice (SQL vs NoSQL)',
        'API design (resources endpoints)',
        'LLD module design (routes services repositories)',
        'Entity & schema design',
        'Explaining trade-offs',
      ],
    },
    {
      id: 'backend-deployment-basics',
      label: 'Deployment Basics',
      iconKey: 'cloud',
      blurb:
        'Hosting frontend (static Vercel-like), hosting backend API, and database hosting basics.',
      rubricFocus: [
        'Hosting frontend',
        'Hosting backend API',
        'Database hosting basics',
        'Environment variables in production',
      ],
      subtopics: [
        'Hosting frontend (static Vercel-like)',
        'Hosting backend API',
        'Database hosting basics',
        'Environment variables in production',
        'Docker basics awareness',
        'README setup & health checks',
        'Explaining a deployed project end-to-end',
      ],
    },
    {
      id: 'backend-git-github',
      label: 'Git & GitHub',
      iconKey: 'git-branch',
      blurb:
        'git init add commit status log, clone push pull, and branching & merging.',
      rubricFocus: [
        'git init add commit status log',
        'Clone push pull',
        'Branching & merging',
        'Pull requests & code review basics',
      ],
      subtopics: [
        'git init add commit status log',
        'Clone push pull',
        'Branching & merging',
        'Pull requests & code review basics',
        'Reading diffs',
        'Merge conflicts intro',
        '.gitignore',
        'Repository hygiene & clean commit history',
      ],
    },
    {
      id: 'backend-dev-tooling',
      label: 'Developer Tooling',
      iconKey: 'wrench',
      blurb:
        'Postman / API clients, package managers (npm pip), and reading docs & debugging mindset.',
      rubricFocus: [
        'Postman / API clients',
        'Package managers',
        'Reading docs & debugging mindset',
      ],
      subtopics: [
        'Postman / API clients',
        'Package managers (npm pip)',
        'Reading docs & debugging mindset',
      ],
    },
  ],
  fullstack: [
    {
      id: 'fullstack-html',
      label: 'HTML',
      iconKey: 'layout-template',
      blurb:
        'Semantic HTML5, document structure (head body), and forms & input types.',
      rubricFocus: [
        'Semantic HTML5',
        'Document structure',
        'Forms & input types',
        'Labels & buttons',
      ],
      subtopics: [
        'Semantic HTML5',
        'Document structure (head body)',
        'Forms & input types',
        'Labels & buttons',
        'Tables & lists',
        'Images & media',
        'Accessibility basics (labels ARIA)',
        'SEO-friendly markup',
        'Cross-browser compatible pages',
      ],
    },
    {
      id: 'fullstack-css',
      label: 'CSS',
      iconKey: 'palette',
      blurb:
        'Selectors (element class id), box model (margin padding border), and colors typography backgrounds borders.',
      rubricFocus: [
        'Selectors',
        'Box model',
        'Colors typography backgrounds borders',
        'Display & positioning',
      ],
      subtopics: [
        'Selectors (element class id)',
        'Box model (margin padding border)',
        'Colors typography backgrounds borders',
        'Display & positioning',
        'Units (px rem % vh vw)',
        'Pseudo-classes & pseudo-elements',
        'Flexbox (direction align justify wrap)',
        'CSS Grid (rows columns areas gaps)',
        'Responsive layouts & media queries',
        'Mobile-first design',
        'Common layouts (header sidebar footer)',
        'CSS frameworks awareness (Bootstrap or Tailwind)',
      ],
    },
    {
      id: 'fullstack-javascript',
      label: 'JavaScript',
      iconKey: 'code',
      blurb:
        'Variables (let const var), data types & type coercion, and operators.',
      rubricFocus: [
        'Variables',
        'Data types & type coercion',
        'Operators',
        'Conditionals',
      ],
      subtopics: [
        'Variables (let const var)',
        'Data types & type coercion',
        'Operators',
        'Conditionals (if else switch)',
        'Loops (for while for...of)',
        'Strings arrays objects',
        'Functions (declarations expressions arrow)',
        'Scope & closures basics',
        'Hoisting intuition',
        'Template literals',
        'Destructuring',
        'Spread & rest',
        'Array methods (map filter reduce forEach find)',
        'Optional chaining & nullish coalescing',
        'Modules (import export)',
        'DOM selectors & manipulation',
        'Events (listeners bubbling delegation)',
        'Form validation',
        'Sync vs async',
        'Callbacks Promises async/await',
        'Fetch API & JSON parsing',
        'Error handling for network calls',
      ],
    },
    {
      id: 'fullstack-how-the-web-works',
      label: 'How the Web Works',
      iconKey: 'network',
      blurb:
        'Client-server model, HTTP methods & status codes, and request-response cycle.',
      rubricFocus: [
        'Client-server model',
        'HTTP methods & status codes',
        'Request-response cycle',
        'Headers cookies sessions',
      ],
      subtopics: [
        'Client-server model',
        'HTTP methods & status codes',
        'Request-response cycle',
        'Headers cookies sessions',
        'CORS basics',
        'REST API consumption from browser',
        'Browser DevTools debugging',
      ],
    },
    {
      id: 'fullstack-react',
      label: 'React',
      iconKey: 'atom',
      blurb:
        'JSX & functional components, props vs state, and useState & useEffect.',
      rubricFocus: [
        'JSX & functional components',
        'Props vs state',
        'useState & useEffect',
        'Conditional rendering',
      ],
      subtopics: [
        'JSX & functional components',
        'Props vs state',
        'useState & useEffect',
        'Conditional rendering',
        'Lists & keys',
        'Controlled forms',
        'Component composition & reusability',
        'Virtual DOM & reconciliation intuition',
        'Lifting state up',
        'Custom hooks basics',
        'React Router (routes navigation)',
        'Context API basics',
        'Fetching data in React (loading error empty states)',
        'localStorage with React',
        'Reusable UI component patterns',
        'Building CRUD UI from scratch',
      ],
    },
    {
      id: 'fullstack-python',
      label: 'Python',
      iconKey: 'terminal',
      blurb: 'Variables & data types, operators, and conditionals.',
      rubricFocus: [
        'Variables & data types',
        'Operators',
        'Conditionals',
        'Loops',
      ],
      subtopics: [
        'Variables & data types',
        'Operators',
        'Conditionals',
        'Loops (for while break continue)',
        'Functions (params return default args scope)',
        'OOP basics (classes objects)',
        'Exception handling',
        'Strings lists tuples dictionaries sets',
        'Indexing slicing & collection methods',
        'Built-in functions (len sorted min max sum)',
        'Nested structures',
        'JSON handling',
        'File I/O',
        'Type hints awareness',
        'Virtual environments (venv)',
        'pip & requirements.txt',
        'Modules packages & project structure',
      ],
    },
    {
      id: 'fullstack-dsa',
      label: 'Basic DSA',
      iconKey: 'sigma',
      blurb: 'Big-O time & space intuition, linear search, and binary search.',
      rubricFocus: [
        'Big-O time & space intuition',
        'Linear search',
        'Binary search',
        'Bubble sort',
      ],
      subtopics: [
        'Big-O time & space intuition',
        'Linear search',
        'Binary search',
        'Bubble sort',
        'Selection sort',
        'Problem decomposition',
        'Nested loops & complexity patterns',
        'Solving structured coding problems with lists strings dicts',
      ],
    },
    {
      id: 'fullstack-http-rest-apis',
      label: 'HTTP & REST APIs',
      iconKey: 'network',
      blurb:
        'Client-server architecture, HTTP methods (GET POST PUT PATCH DELETE), and status codes.',
      rubricFocus: [
        'Client-server architecture',
        'HTTP methods',
        'Status codes',
        'Headers & body',
      ],
      subtopics: [
        'Client-server architecture',
        'HTTP methods (GET POST PUT PATCH DELETE)',
        'Status codes',
        'Headers & body',
        'REST resources & endpoints',
        'API contracts (request response errors)',
        'Pagination filtering sorting',
        'Idempotency & safe methods intuition',
        'Testing APIs with Postman or Swagger',
      ],
    },
    {
      id: 'fullstack-fastapi',
      label: 'FastAPI',
      iconKey: 'code',
      blurb:
        'Project setup & first endpoints, path & query parameters, and request body & response models.',
      rubricFocus: [
        'Project setup & first endpoints',
        'Path & query parameters',
        'Request body & response models',
        'Full CRUD APIs',
      ],
      subtopics: [
        'Project setup & first endpoints',
        'Path & query parameters',
        'Request body & response models',
        'Full CRUD APIs',
        'Pydantic schemas & validation',
        'Dependency injection',
        'Middleware',
        'CORS configuration',
        'Background tasks',
        'File upload/download',
        'Environment variables & config',
        'OpenAPI / Swagger UI',
        'Async awareness (async await)',
        'Integrating third-party APIs',
      ],
    },
    {
      id: 'fullstack-sql',
      label: 'SQL',
      iconKey: 'database',
      blurb:
        'Relational DB concepts, CREATE TABLE & data types, and INSERT SELECT UPDATE DELETE.',
      rubricFocus: [
        'Relational DB concepts',
        'CREATE TABLE & data types',
        'INSERT SELECT UPDATE DELETE',
        'WHERE ORDER BY LIMIT',
      ],
      subtopics: [
        'Relational DB concepts',
        'CREATE TABLE & data types',
        'INSERT SELECT UPDATE DELETE',
        'WHERE ORDER BY LIMIT',
        'Primary & foreign keys',
        'Relationships (1:1 1:N N:M)',
        'INNER JOIN & LEFT JOIN',
        'Aggregates (COUNT SUM AVG MIN MAX)',
        'GROUP BY & HAVING',
        'Subqueries basics',
        'Indexes intuition',
        'PostgreSQL/MySQL familiarity',
      ],
    },
    {
      id: 'fullstack-orm-sqlalchemy',
      label: 'ORM (SQLAlchemy)',
      iconKey: 'database',
      blurb: 'ORM vs raw SQL, models & sessions, and CRUD with ORM.',
      rubricFocus: [
        'ORM vs raw SQL',
        'Models & sessions',
        'CRUD with ORM',
        'One-to-many relationships',
      ],
      subtopics: [
        'ORM vs raw SQL',
        'Models & sessions',
        'CRUD with ORM',
        'One-to-many relationships',
        'Filtering & joins via ORM',
        'Integrating ORM with FastAPI',
        'Migrations awareness (Alembic basics)',
      ],
    },
    {
      id: 'fullstack-auth-api-security',
      label: 'Auth & API Security',
      iconKey: 'shield-check',
      blurb:
        'Password hashing intuition, JWT / token auth basics, and protected routes.',
      rubricFocus: [
        'Password hashing intuition',
        'JWT / token auth basics',
        'Protected routes',
        'OAuth2 awareness',
      ],
      subtopics: [
        'Password hashing intuition',
        'JWT / token auth basics',
        'Protected routes',
        'OAuth2 awareness',
        'Input validation & sanitization',
        'Common API security mistakes',
        'Secrets & .env management',
      ],
    },
    {
      id: 'fullstack-genai-llm-apis',
      label: 'GenAI & LLM APIs',
      iconKey: 'sparkle',
      blurb:
        'LLM fundamentals, prompt engineering (system prompts chains), and structured outputs (JSON).',
      rubricFocus: [
        'LLM fundamentals',
        'Prompt engineering',
        'Structured outputs',
        'Calling OpenAI Anthropic or similar APIs',
      ],
      subtopics: [
        'LLM fundamentals',
        'Prompt engineering (system prompts chains)',
        'Structured outputs (JSON)',
        'Calling OpenAI Anthropic or similar APIs',
        'Auth rate limits & token cost awareness',
        'Streaming responses basics',
        'Embeddings overview',
        'RAG basics (retrieve then generate)',
        'Wiring LLM features into FastAPI services',
      ],
    },
    {
      id: 'fullstack-fullstack-integration',
      label: 'Full Stack Integration',
      iconKey: 'stack',
      blurb:
        'Frontend-backend separation, API as contract between FE & BE, and end-to-end request flow (UI → API → DB → UI).',
      rubricFocus: [
        'Frontend-backend separation',
        'API as contract between FE & BE',
        'End-to-end request flow',
        'Fetch/axios from React to FastAPI',
      ],
      subtopics: [
        'Frontend-backend separation',
        'API as contract between FE & BE',
        'End-to-end request flow (UI → API → DB → UI)',
        'Fetch/axios from React to FastAPI',
        'CORS in real apps',
        'Auth token flow (login store attach header)',
        'Error loading empty states across stack',
        'Client state vs server state',
        'Pagination end-to-end',
        'Designing entities routes & React CRUD screens',
        'Validation on both FE & BE',
        'Mini project patterns (Todo Notes Inventory)',
      ],
    },
    {
      id: 'fullstack-hld-lld-basics',
      label: 'HLD / LLD Basics',
      iconKey: 'network',
      blurb:
        'HLD vs LLD difference, drawing high-level architecture (client API DB), and monolith vs microservices intuition.',
      rubricFocus: [
        'HLD vs LLD difference',
        'Drawing high-level architecture',
        'Monolith vs microservices intuition',
        'Caching & scaling basics',
      ],
      subtopics: [
        'HLD vs LLD difference',
        'Drawing high-level architecture (client API DB)',
        'Monolith vs microservices intuition',
        'Caching & scaling basics',
        'Database choice (SQL vs NoSQL)',
        'API design (resources endpoints)',
        'LLD module design (routes services repositories)',
        'Entity & schema design',
        'Explaining trade-offs',
      ],
    },
    {
      id: 'fullstack-deployment-basics',
      label: 'Deployment Basics',
      iconKey: 'cloud',
      blurb:
        'Hosting frontend (static Vercel-like), hosting backend API, and database hosting basics.',
      rubricFocus: [
        'Hosting frontend',
        'Hosting backend API',
        'Database hosting basics',
        'Environment variables in production',
      ],
      subtopics: [
        'Hosting frontend (static Vercel-like)',
        'Hosting backend API',
        'Database hosting basics',
        'Environment variables in production',
        'Docker basics awareness',
        'README setup & health checks',
        'Explaining a deployed project end-to-end',
      ],
    },
    {
      id: 'fullstack-git-github',
      label: 'Git & GitHub',
      iconKey: 'git-branch',
      blurb:
        'git init add commit status log, clone push pull, and branching & merging.',
      rubricFocus: [
        'git init add commit status log',
        'Clone push pull',
        'Branching & merging',
        'Pull requests & code review basics',
      ],
      subtopics: [
        'git init add commit status log',
        'Clone push pull',
        'Branching & merging',
        'Pull requests & code review basics',
        'Merge conflicts intro',
        '.gitignore',
        'Repository hygiene & clean commit history',
      ],
    },
    {
      id: 'fullstack-dev-tooling',
      label: 'Developer Tooling',
      iconKey: 'wrench',
      blurb:
        'VS Code & terminal workflow, browser DevTools, and postman / API clients.',
      rubricFocus: [
        'VS Code & terminal workflow',
        'Browser DevTools',
        'Postman / API clients',
        'Package managers',
      ],
      subtopics: [
        'VS Code & terminal workflow',
        'Browser DevTools',
        'Postman / API clients',
        'Package managers (npm pip)',
        'Reading docs & debugging mindset',
      ],
    },
  ],
  'digital-marketing': [
    {
      id: 'digital-marketing-dm-fundamentals',
      label: 'Digital Marketing Fundamentals & Strategy',
      iconKey: 'megaphone',
      blurb:
        'Marketing Mix (4Ps/7Ps), marketing Funnel & AIDA(S) Framework, and consumer Behaviour & Buyer Journey.',
      rubricFocus: [
        'Marketing Mix',
        'Marketing Funnel & AIDA(S) Framework',
        'Consumer Behaviour & Buyer Journey',
        'STP',
      ],
      subtopics: [
        'Marketing Mix (4Ps/7Ps)',
        'Marketing Funnel & AIDA(S) Framework',
        'Consumer Behaviour & Buyer Journey',
        'STP (Segmentation, Targeting, Positioning)',
        'Branding & Positioning',
        'Integrated Marketing Communications',
        'Digital Strategy & Business Models',
        'Marketing Budgeting & Planning',
        'Customer Centricity',
        'Marketing KPIs & Metrics',
        'Competitive Analysis',
      ],
    },
    {
      id: 'digital-marketing-seo',
      label: 'Search Engine Optimization (SEO)',
      iconKey: 'magnifying-glass',
      blurb: 'On-Page SEO, off-Page SEO & Link Building, and technical SEO.',
      rubricFocus: [
        'On-Page SEO',
        'Off-Page SEO & Link Building',
        'Technical SEO',
        'Keyword Research & Search Intent',
      ],
      subtopics: [
        'On-Page SEO',
        'Off-Page SEO & Link Building',
        'Technical SEO',
        'Keyword Research & Search Intent',
        'SEO Tools (SEMrush, Ahrefs, Google Search Console)',
        'Local SEO',
        'SEO Content Strategy',
        'Answer Engine Optimization & Generative Search (SGE/AI Overviews)',
        'SEO Measurement & Reporting',
        'Core Web Vitals',
      ],
    },
    {
      id: 'digital-marketing-sem-paid-ads',
      label: 'Search Engine Marketing (SEM) & Paid Advertising',
      iconKey: 'currency-dollar',
      blurb:
        'Google Ads Campaign Structure, PPC Fundamentals, and audience Targeting & Bidding Strategies.',
      rubricFocus: [
        'Google Ads Campaign Structure',
        'PPC Fundamentals',
        'Audience Targeting & Bidding Strategies',
        'Ad Copywriting',
      ],
      subtopics: [
        'Google Ads Campaign Structure',
        'PPC Fundamentals',
        'Audience Targeting & Bidding Strategies',
        'Ad Copywriting',
        'Display Advertising',
        'Quality Score & Ad Rank',
        'AI-Powered Ad Creation',
        'Campaign Measurement & Attribution',
        'Media Planning & Budget Allocation',
        'Retargeting & Remarketing',
      ],
    },
    {
      id: 'digital-marketing-social-media-marketing',
      label: 'Social Media Marketing',
      iconKey: 'chat-circle',
      blurb:
        'Platform Strategy (Instagram, Facebook, LinkedIn, X, YouTube), content Calendar & Strategy, and community Management.',
      rubricFocus: [
        'Platform Strategy',
        'Content Calendar & Strategy',
        'Community Management',
        'Influencer & Creator Marketing',
      ],
      subtopics: [
        'Platform Strategy (Instagram, Facebook, LinkedIn, X, YouTube)',
        'Content Calendar & Strategy',
        'Community Management',
        'Influencer & Creator Marketing',
        'Paid Social Advertising',
        'Social Media Analytics',
        'Social Listening',
        'B2B Social Media Marketing',
        'Personal Branding on LinkedIn',
        'AI Tools for Social Content',
      ],
    },
    {
      id: 'digital-marketing-content-marketing',
      label: 'Content Marketing & Creative',
      iconKey: 'palette',
      blurb:
        'Content Strategy & Planning, copywriting Fundamentals, and SEO Content Writing.',
      rubricFocus: [
        'Content Strategy & Planning',
        'Copywriting Fundamentals',
        'SEO Content Writing',
        'Storytelling & Brand Voice',
      ],
      subtopics: [
        'Content Strategy & Planning',
        'Copywriting Fundamentals',
        'SEO Content Writing',
        'Storytelling & Brand Voice',
        'AI-Powered Content Creation',
        'Video & Visual Content Marketing',
        'Content Distribution & Repurposing',
        'Content Performance Measurement',
      ],
    },
    {
      id: 'digital-marketing-email-crm-automation',
      label: 'Email Marketing, CRM & Marketing Automation',
      iconKey: 'envelope-simple',
      blurb:
        'Email Campaign Fundamentals, list Segmentation & Personalization, and marketing Automation Workflows.',
      rubricFocus: [
        'Email Campaign Fundamentals',
        'List Segmentation & Personalization',
        'Marketing Automation Workflows',
        'AI-Powered Email Marketing',
      ],
      subtopics: [
        'Email Campaign Fundamentals',
        'List Segmentation & Personalization',
        'Marketing Automation Workflows',
        'AI-Powered Email Marketing',
        'CRM Fundamentals',
        'Lead Nurturing & Lifecycle Marketing',
        'A/B Testing for Email',
        'Deliverability & Compliance (GDPR/CAN-SPAM)',
      ],
    },
    {
      id: 'digital-marketing-marketing-analytics',
      label: 'Marketing Analytics & Data',
      iconKey: 'chart-line',
      blurb:
        'Google Analytics 4 (GA4), web Analytics Fundamentals, and marketing Attribution Models.',
      rubricFocus: [
        'Google Analytics 4',
        'Web Analytics Fundamentals',
        'Marketing Attribution Models',
        'Customer Segmentation & Clustering',
      ],
      subtopics: [
        'Google Analytics 4 (GA4)',
        'Web Analytics Fundamentals',
        'Marketing Attribution Models',
        'Customer Segmentation & Clustering',
        'Dashboards & Data Visualization',
        'A/B Testing & Experimentation',
        'Predictive Analytics',
        'Conversion Rate Optimization (CRO)',
        'Customer Lifetime Value (CLV) & Retention Metrics',
        'Marketing Mix Modeling',
      ],
    },
    {
      id: 'digital-marketing-ai-in-marketing',
      label: 'AI & Emerging Technologies in Marketing',
      iconKey: 'sparkle',
      blurb:
        'Generative AI for Marketing, prompt Engineering, and agentic AI Applications.',
      rubricFocus: [
        'Generative AI for Marketing',
        'Prompt Engineering',
        'Agentic AI Applications',
        'AI Image/Audio/Video Generation',
      ],
      subtopics: [
        'Generative AI for Marketing',
        'Prompt Engineering',
        'Agentic AI Applications',
        'AI Image/Audio/Video Generation',
        'Marketing Technology (Martech) Stack',
        'AR/VR & Immersive Marketing',
        'Voice Search & Conversational Commerce',
        'Chatbots & Conversational Marketing',
        'AI Ethics',
        'Privacy & Data Governance',
      ],
    },
    {
      id: 'digital-marketing-ecommerce-growth',
      label: 'E-commerce & Growth Marketing',
      iconKey: 'shopping-cart',
      blurb:
        'E-commerce Platforms & Ecosystems, UX/UI & Conversion Architecture, and affiliate Marketing.',
      rubricFocus: [
        'E-commerce Platforms & Ecosystems',
        'UX/UI & Conversion Architecture',
        'Affiliate Marketing',
        'Omnichannel & Retail Media Strategy',
      ],
      subtopics: [
        'E-commerce Platforms & Ecosystems',
        'UX/UI & Conversion Architecture',
        'Affiliate Marketing',
        'Omnichannel & Retail Media Strategy',
        'Growth Hacking & Viral Loops',
        'Online Reputation Management',
        'Marketplace Optimization (Amazon/Flipkart)',
      ],
    },
  ],
  'product-management': [
    {
      id: 'product-management-pm-foundations',
      label: 'Product Management Foundations & PM Mindset',
      iconKey: 'lightbulb',
      blurb:
        'Product Management Ecosystem & PM Archetypes, PM Toolkit (Jira, Figma, Slack, Notion), and product Health Frameworks (AARRR, HEART, Kano).',
      rubricFocus: [
        'Product Management Ecosystem & PM Archetypes',
        'PM Toolkit',
        'Product Health Frameworks',
        'Product Lifecycle Management',
      ],
      subtopics: [
        'Product Management Ecosystem & PM Archetypes',
        'PM Toolkit (Jira, Figma, Slack, Notion)',
        'Product Health Frameworks (AARRR, HEART, Kano)',
        'Product Lifecycle Management',
        'Product Vision & Mission',
        'Types of Product Managers by Company Stage',
        'Ethics in Product Management',
      ],
    },
    {
      id: 'product-management-user-research',
      label: 'User Research & Discovery',
      iconKey: 'magnifying-glass',
      blurb:
        'User Research Methods (Interviews, Surveys, Observation), user Interview Techniques, and empathy Mapping & Affinity Clustering.',
      rubricFocus: [
        'User Research Methods',
        'User Interview Techniques',
        'Empathy Mapping & Affinity Clustering',
        'User Personas & Jobs-to-be-Done',
      ],
      subtopics: [
        'User Research Methods (Interviews, Surveys, Observation)',
        'User Interview Techniques',
        'Empathy Mapping & Affinity Clustering',
        'User Personas & Jobs-to-be-Done',
        'Competitive Teardown & Opportunity Assessment',
        'SWOT Analysis',
        'Design Thinking (Empathize-Define-Ideate-Prototype-Test)',
        'Customer Journey Mapping',
        'Market Research Techniques',
      ],
    },
    {
      id: 'product-management-product-strategy',
      label: 'Product Strategy & Market Analysis',
      iconKey: 'target',
      blurb:
        'Product Strategy Formulation, market & Environment Scanning, and TAM/SAM/SOM Market Sizing.',
      rubricFocus: [
        'Product Strategy Formulation',
        'Market & Environment Scanning',
        'TAM/SAM/SOM Market Sizing',
        'Positioning Statements',
      ],
      subtopics: [
        'Product Strategy Formulation',
        'Market & Environment Scanning',
        'TAM/SAM/SOM Market Sizing',
        'Positioning Statements',
        'Platform Strategy',
        'Feasibility Analysis',
        'Product Propositions & Ideation',
        'Evaluating & Critiquing Strategy',
        'Sustainable Product Management',
      ],
    },
    {
      id: 'product-management-product-design-ux',
      label: 'Product Design, UX & Prototyping',
      iconKey: 'palette',
      blurb:
        'Wireframing & Prototyping (Figma), usability Testing & Concept Validation, and writing PRDs.',
      rubricFocus: [
        'Wireframing & Prototyping',
        'Usability Testing & Concept Validation',
        'Writing PRDs',
        'User Stories & INVEST Criteria',
      ],
      subtopics: [
        'Wireframing & Prototyping (Figma)',
        'Usability Testing & Concept Validation',
        'Writing PRDs',
        'User Stories & INVEST Criteria',
        'MVP Types & Scoping (Concierge, Wizard of Oz, Demo)',
        'UX/UI Best Practices',
        'Feature Prioritization Frameworks (RICE, MoSCoW)',
      ],
    },
    {
      id: 'product-management-agile-execution',
      label: 'Product Development, Agile & Execution',
      iconKey: 'list-checks',
      blurb:
        'Agile Ceremonies & Scrum Framework, sprint Planning & Backlog Grooming, and jira for Execution & Tracking.',
      rubricFocus: [
        'Agile Ceremonies & Scrum Framework',
        'Sprint Planning & Backlog Grooming',
        'Jira for Execution & Tracking',
        'Translating Product Vision to Sprints',
      ],
      subtopics: [
        'Agile Ceremonies & Scrum Framework',
        'Sprint Planning & Backlog Grooming',
        'Jira for Execution & Tracking',
        'Translating Product Vision to Sprints',
        'Technology Selection & Development Basics',
        'Deployment & Release Management',
        'Technical Debt vs New Features Trade-offs',
        'Project Management Fundamentals',
      ],
    },
    {
      id: 'product-management-gtm-growth',
      label: 'Go-To-Market & Growth',
      iconKey: 'rocket',
      blurb:
        'GTM Strategy & Launch Planning, pricing & Packaging Models (Freemium, Value-based, Usage-based), and business Model Analysis.',
      rubricFocus: [
        'GTM Strategy & Launch Planning',
        'Pricing & Packaging Models',
        'Business Model Analysis',
        'Product-Led vs Sales-Led Growth',
      ],
      subtopics: [
        'GTM Strategy & Launch Planning',
        'Pricing & Packaging Models (Freemium, Value-based, Usage-based)',
        'Business Model Analysis',
        'Product-Led vs Sales-Led Growth',
        'Growth Loops & Viral Mechanics',
        'Sales & Distribution Strategy',
        'Branding & Positioning',
        'Promotion Strategy (7Ps)',
        'Digital Marketing Fundamentals for PMs',
        'Consumer Behaviour',
        'Customer Service Strategy',
      ],
    },
    {
      id: 'product-management-product-analytics',
      label: 'Product Analytics, Metrics & Experimentation',
      iconKey: 'chart-line',
      blurb:
        'Product Metrics & North Star KPIs, funnel Analysis & Retention Cohorts (Mixpanel), and a/B Testing & Experimentation Design.',
      rubricFocus: [
        'Product Metrics & North Star KPIs',
        'Funnel Analysis & Retention Cohorts',
        'A/B Testing & Experimentation Design',
        'Statistical Significance & Sample Sizing',
      ],
      subtopics: [
        'Product Metrics & North Star KPIs',
        'Funnel Analysis & Retention Cohorts (Mixpanel)',
        'A/B Testing & Experimentation Design',
        'Statistical Significance & Sample Sizing',
        'Data-Driven Decision Making',
        'Regression Analysis Basics',
        'Customer Lifetime Value (CLV)',
        'Digital & Media Metrics',
        'KPI Dashboards & Reporting',
        'Analytics Tool Comparison (GA4 vs Mixpanel)',
      ],
    },
    {
      id: 'product-management-ai-in-pm',
      label: 'AI & Emerging Tech in Product Management',
      iconKey: 'sparkle',
      blurb:
        'AI/ML/LLM Foundations for PMs, prompt Engineering (Role-Context-Format), and build vs Buy vs Fine-tune Decisions.',
      rubricFocus: [
        'AI/ML/LLM Foundations for PMs',
        'Prompt Engineering',
        'Build vs Buy vs Fine-tune Decisions',
        'Responsible & Ethical AI / Bias Mitigation',
      ],
      subtopics: [
        'AI/ML/LLM Foundations for PMs',
        'Prompt Engineering (Role-Context-Format)',
        'Build vs Buy vs Fine-tune Decisions',
        'Responsible & Ethical AI / Bias Mitigation',
        'AI Product Teardowns & Competitive Analysis',
        'AI-Driven UX & Adaptive Interfaces',
        'Agentic AI Foundations & Architectures',
        'No-Code AI Product Building (Airtable, Glide, Zapier, OpenAI API)',
        'AI Safety',
        'Privacy & Risk Assessment',
        'AI-Specific Metrics (accuracy, cost per token, time-to-value)',
      ],
    },
    {
      id: 'product-management-stakeholder-management',
      label: 'Stakeholder Management & Leadership',
      iconKey: 'handshake',
      blurb:
        'Stakeholder Communication & Alignment, power/Interest Mapping, and leading Without Authority.',
      rubricFocus: [
        'Stakeholder Communication & Alignment',
        'Power/Interest Mapping',
        'Leading Without Authority',
        'Cross-functional Team Collaboration',
      ],
      subtopics: [
        'Stakeholder Communication & Alignment',
        'Power/Interest Mapping',
        'Leading Without Authority',
        'Cross-functional Team Collaboration',
        'Executive Summaries & Status Updates',
        'Product Failure Case Studies & Root Cause Analysis',
        'Conflict Resolution & Prioritization Trade-offs',
      ],
    },
  ],
  'data-analytics': [
    {
      id: 'data-analytics-sql',
      label: 'SQL',
      iconKey: 'database',
      blurb:
        'RDBMS concepts (tables, rows, columns, schema, primary & foreign keys), SELECT & DISTINCT, and WHERE filtering.',
      rubricFocus: [
        'RDBMS concepts',
        'SELECT & DISTINCT',
        'WHERE filtering',
        'Comparison & logical operators',
      ],
      subtopics: [
        'RDBMS concepts (tables, rows, columns, schema, primary & foreign keys)',
        'SELECT & DISTINCT',
        'WHERE filtering',
        'Comparison & logical operators (AND, OR, NOT, IN, BETWEEN, LIKE, IS NULL)',
        'ORDER BY & LIMIT',
        'Aliases',
        'Aggregate functions (COUNT, SUM, AVG, MIN, MAX)',
        'GROUP BY & HAVING (vs WHERE)',
        'CASE WHEN',
        'String & date functions',
        'Joins (Inner, Left, Right, Full Outer, Self, Cross)',
        'Predicting & diagnosing join row counts',
        'Set operations (UNION, INTERSECT, EXCEPT)',
        'Subqueries (in WHERE/SELECT/FROM, correlated vs uncorrelated)',
        'CTEs (incl. chaining multiple CTEs)',
        'Window functions (ROW_NUMBER, RANK, DENSE_RANK, PARTITION BY, LAG, LEAD , running totals, moving averages)',
        'Indexes & query performance',
        'Query execution plans & diagnosing slow queries',
        'Mapping SQL operations to Pandas equivalents',
      ],
    },
    {
      id: 'data-analytics-python-libraries',
      label: 'Python & Libraries',
      iconKey: 'terminal',
      blurb:
        'Variables & core data types (int, float, string, boolean), arithmetic, and comparison & logical operators.',
      rubricFocus: [
        'Variables & core data types',
        'Arithmetic',
        'comparison & logical operators',
        'Type conversion',
      ],
      subtopics: [
        'Variables & core data types (int, float, string, boolean)',
        'Arithmetic',
        'comparison & logical operators',
        'Type conversion',
        'Conditionals (if, elif, else)',
        'Loops (for, while, break, continue)',
        'Functions (parameters, return values, default & keyword arguments, scope)',
        'Lambda functions',
        'Data structures (lists, tuples, dictionaries, sets)',
        'String creation',
        'indexing',
        'slicing & methods',
        'f-strings',
        'List/dict/set comprehensions',
        'File I/O & context managers (with)',
        'Exception handling (try, except, finally, custom exceptions)',
        'Modules',
        'packages & imports',
        'Object-Oriented Programming (classes & objects, __init__ constructor, instance vs class attributes, methods, inheritance, encapsulation, polymorphism, dunder/magic methods, dataclasses)',
        'Iterators & generators',
        'Decorators (basic use)',
        'Working with JSON (parsing, nested structures)',
        'Calling APIs (requests library, GET/POST, status codes, auth, rate limits)',
        'Environment variables & secrets management',
        'Git & GitHub basics (init, commit, push, branches)',
        'Google Colab & Jupyter Notebook workflow',
        'Array creation',
        'shape & dtype',
        'Indexing',
        'slicing & boolean masking',
        'Vectorized arithmetic & comparisons',
        'NumPy arrays vs plain Python lists',
        'Broadcasting rules',
        'Aggregations along axes (sum, mean, min, max, std)',
        'Reshape',
        'transpose & stack',
        'Random number generation',
        'Linear algebra basics (dot product, matrix multiplication)',
        'Series & DataFrames',
        'Reading/writing data (CSV, Excel, JSON, SQL)',
        'Inspecting data (head, info, describe, shape, dtypes, value_counts, nunique)',
        'Selection & filtering (loc, iloc, boolean indexing)',
        'Handling missing values (isnull, dropna, fillna)',
        'Removing duplicates & fixing inconsistent categories',
        'Data type conversion (astype)',
        'Vectorized string operations on columns',
        'Sorting & ranking',
        'GroupBy & aggregation (agg, multiple keys, custom functions)',
        'Merging',
        'joining & concatenation (inner, left, right, outer)',
        'Reshaping data (pivot_table, melt, crosstab)',
        'Date & time handling',
        'Applying custom functions (apply, map, lambda)',
        'Window & rolling operations',
      ],
    },
    {
      id: 'data-analytics-data-viz-eda',
      label: 'Data Visualization & EDA',
      iconKey: 'chart-bar',
      blurb:
        'Figures, axes & subplots, and plot types (line, bar, scatter, histogram, box plot, heatmap, pair plot).',
      rubricFocus: [
        'Figures',
        'axes & subplots',
        'Plot types',
        'Plotting directly from Pandas DataFrames',
      ],
      subtopics: [
        'Figures',
        'axes & subplots',
        'Plot types (line, bar, scatter, histogram, box plot, heatmap, pair plot)',
        'Plotting directly from Pandas DataFrames',
        'Styling (titles, labels, legends, colors, annotations)',
        'Seaborn statistical plots (distribution plots, box plots, correlation heatmaps)',
        'Exporting presentation-ready charts',
        'Choosing the right chart type for the data & question',
        'Structured EDA workflow (question, explore, interpret)',
        'Univariate',
        'bivariate & multivariate analysis',
        'Descriptive statistics (mean, median, mode, variance, standard deviation)',
        'Distribution shape',
        'skewness & outlier effects on mean vs median',
        'Outlier detection (IQR method, z-score, box plots)',
        'Correlation analysis & correlation vs causation',
        'Missing value analysis & treatment strategy',
        'Data cleaning (duplicates, inconsistent categories, type fixes)',
        'Feature relationships & hypothesis generation',
        'Cohort',
        'funnel & retention analysis basics',
      ],
    },
    {
      id: 'data-analytics-excel-spreadsheets',
      label: 'Excel & Spreadsheets',
      iconKey: 'table',
      blurb:
        'Interface & cell referencing (relative, absolute, mixed), core functions (SUM, AVERAGE, COUNT, COUNTA, COUNTIF, AVERAGEIF, IF, nested IF), and filtering & sorting (single & multi-column).',
      rubricFocus: [
        'Interface & cell referencing',
        'Core functions',
        'Filtering & sorting',
        'Conditional formatting',
      ],
      subtopics: [
        'Interface & cell referencing (relative, absolute, mixed)',
        'Core functions (SUM, AVERAGE, COUNT, COUNTA, COUNTIF, AVERAGEIF, IF, nested IF)',
        'Filtering & sorting (single & multi-column)',
        'Conditional formatting',
        'Data validation',
        'Text & date functions (TRIM, SPLIT, CONCAT, date arithmetic)',
        'Lookup functions (VLOOKUP, HLOOKUP, XLOOKUP, INDEX & MATCH)',
        'Error handling (IFERROR, IFNA)',
        'Pivot Tables (rows, columns, values, filters, grouping by date/number/category)',
        'Pivot Charts & slicers',
        'Dashboard design (layout, KPIs, interactive elements, dynamic charts)',
        'Named ranges',
        'What-if analysis (Goal Seek, Data Tables, Scenario Manager)',
        'Power Query for data cleaning & light ETL',
        'Macros & VBA basics for repetitive tasks',
      ],
    },
    {
      id: 'data-analytics-statistics-probability',
      label: 'Statistics & Probability',
      iconKey: 'sigma',
      blurb:
        'Descriptive statistics (mean, median, mode, range, variance, standard deviation), types & scales of data (nominal, ordinal, interval, ratio), and probability basics (classical, empirical, subjective).',
      rubricFocus: [
        'Descriptive statistics',
        'Types & scales of data',
        'Probability basics',
        'Sample spaces & events',
      ],
      subtopics: [
        'Descriptive statistics (mean, median, mode, range, variance, standard deviation)',
        'Types & scales of data (nominal, ordinal, interval, ratio)',
        'Probability basics (classical, empirical, subjective)',
        'Sample spaces & events',
        'Addition & multiplication rules',
        "Conditional probability & Bayes' theorem",
        'Probability distributions (PDF vs CDF, normal, binomial, poisson)',
        'Central Limit Theorem',
        'Correlation vs causation',
        'Covariance & correlation coefficient',
        'Sampling & sample-size intuition',
        'Standard error & margin of error',
        'Confidence intervals (construction & interpretation)',
        'Null vs alternative hypothesis',
        'Significance level (alpha) & p-value interpretation',
        'Type I vs Type II errors',
        'One-tailed vs two-tailed tests',
        'One-sample & two-sample z-test',
        'One-sample',
        'paired & independent-samples t-test',
        'Chi-square test (goodness of fit & independence)',
        'ANOVA (one-way & two-way) for comparing multiple groups',
        'Non-parametric tests (Mann-Whitney U, Kruskal-Wallis) when assumptions fail',
        "Effect size (Cohen's d)",
        'Statistical power & sample size calculation',
        'Multiple testing correction (Bonferroni, FDR)',
        'Common pitfalls (p-hacking, misreading p-values, correlation vs causation traps)',
      ],
    },
    {
      id: 'data-analytics-ab-testing',
      label: 'A/B Testing & Experimentation',
      iconKey: 'target',
      blurb:
        'Formulating a testable hypothesis & success metric, randomization & control vs treatment groups, and sample size & test duration calculation (power analysis).',
      rubricFocus: [
        'Formulating a testable hypothesis & success metric',
        'Randomization & control vs treatment groups',
        'Sample size & test duration calculation',
        'Running & monitoring an experiment',
      ],
      subtopics: [
        'Formulating a testable hypothesis & success metric',
        'Randomization & control vs treatment groups',
        'Sample size & test duration calculation (power analysis)',
        'Running & monitoring an experiment',
        'Statistical significance vs practical significance',
        'Novelty effects & seasonality confounds',
        'Guardrail metrics & avoiding peeking bias',
        'Interpreting & communicating experiment results',
        'Sequential testing & multi-armed bandits (advanced)',
      ],
    },
    {
      id: 'data-analytics-tableau',
      label: 'Tableau',
      iconKey: 'chart-bar',
      blurb:
        'Interface & connecting to data, live connections vs extracts, and worksheets & shelves.',
      rubricFocus: [
        'Interface & connecting to data',
        'Live connections vs extracts',
        'Worksheets & shelves',
        'Chart types',
      ],
      subtopics: [
        'Interface & connecting to data',
        'Live connections vs extracts',
        'Worksheets & shelves',
        'Chart types (bar, line, scatter, map, dual-axis, combo, treemap, bullet, waterfall)',
        'Choosing the right chart type for the question',
        'Formatting for clarity (titles, labels, tooltips, colors)',
        'Sets & groups',
        'Calculated fields & table calculations (running total, moving average, percent of total)',
        'LOD expressions (FIXED, INCLUDE, EXCLUDE)',
        'Trend lines & basic forecasting',
        'Filters',
        'filter actions & highlight actions',
        'Parameters & what-if scenarios',
        'Dashboard layout & containers',
        'Combining worksheets into a single dashboard',
        'Tableau Story Points for narrative dashboards',
        'Publishing & sharing (Tableau Server, Tableau Public, Tableau Cloud)',
        'Performance optimization for large datasets',
      ],
    },
    {
      id: 'data-analytics-power-bi',
      label: 'Power BI',
      iconKey: 'chart-pie',
      blurb:
        'Interface & Power Query Editor, connecting & transforming data (ETL, Power Query M language basics), and data modeling (relationships, star vs snowflake schema, cardinality).',
      rubricFocus: [
        'Interface & Power Query Editor',
        'Connecting & transforming data',
        'Data modeling',
        'DAX basics',
      ],
      subtopics: [
        'Interface & Power Query Editor',
        'Connecting & transforming data (ETL, Power Query M language basics)',
        'Data modeling (relationships, star vs snowflake schema, cardinality)',
        'DAX basics (calculated columns vs measures)',
        'DAX intermediate (CALCULATE, time intelligence functions, iterators SUMX/AVERAGEX)',
        'Visualizations (bar, line, matrix, map, card, slicer, combo, custom visuals)',
        'Report design & layout',
        'Interactivity (slicers, drill-through, bookmarks, tooltips, what-if parameters)',
        'Dashboards vs reports',
        'Row-level security',
        'Power BI Desktop vs Power BI Service',
        'Publishing & sharing',
        'Scheduled refresh & Power BI Gateway',
        'Natural-language Q&A visuals',
      ],
    },
    {
      id: 'data-analytics-data-storytelling-ai',
      label: 'Data Storytelling & AI-Assisted Analytics',
      iconKey: 'sparkle',
      blurb:
        "Framing findings around the audience's question or decision, choosing the visual that best supports a message, and dashboard narrative structure (headline, context, insight, recommendation).",
      rubricFocus: [
        "Framing findings around the audience's question or decision",
        'Choosing the visual that best supports a message',
        'Dashboard narrative structure',
        'Stakeholder mapping & requirements gathering',
      ],
      subtopics: [
        "Framing findings around the audience's question or decision",
        'Choosing the visual that best supports a message',
        'Dashboard narrative structure (headline, context, insight, recommendation)',
        'Stakeholder mapping & requirements gathering',
        'Distinguishing a business need from a proposed solution',
        'KPI design (metric, target, timeframe)',
        'Presenting insights (PowerPoint, Google Slides, Notion)',
        'Avoiding misleading visuals',
        'Prompt structure for analyst tasks (task, context, constraints, format)',
        'Generating & verifying SQL queries and Excel formulas with AI',
        'Analyzing datasets with ChatGPT Data Analysis / Claude',
        'Spotting hallucinations & sanity-checking AI output',
        'Iterating & refining prompts',
        'Drafting insight summaries & report narratives with AI',
        'Critiquing charts & dashboards with AI',
        'Building a reusable analyst prompt library',
        'Configuring a custom GPT / Claude Project as a recurring analyst assistant',
      ],
    },
    {
      id: 'data-analytics-data-warehousing-governance',
      label: 'Data Warehousing, Governance & Product Analytics',
      iconKey: 'database',
      blurb:
        'Databases vs data warehouses vs data lakes, OLTP vs OLAP, and dimensional modeling (fact & dimension tables, star vs snowflake schema).',
      rubricFocus: [
        'Databases vs data warehouses vs data lakes',
        'OLTP vs OLAP',
        'Dimensional modeling',
        'ETL vs ELT',
      ],
      subtopics: [
        'Databases vs data warehouses vs data lakes',
        'OLTP vs OLAP',
        'Dimensional modeling (fact & dimension tables, star vs snowflake schema)',
        'ETL vs ELT',
        'Batch vs streaming pipelines (conceptual)',
        'Data quality checks (missing data, outliers, duplicates, schema drift)',
        'Data governance',
        'stewardship & cataloging',
        'Metrics vs KPIs',
        'Analytics maturity spectrum (descriptive, diagnostic, predictive, prescriptive)',
        'Key business/product metrics (DAU/MAU, conversion rate, churn, retention, CAC, LTV)',
        'Event tracking & data layer basics',
        'Google Analytics 4 (GA4) fundamentals',
        'UTM parameters & campaign tracking',
        'Funnel analysis & drop-off diagnosis',
        'Cohort & retention curves',
        'Dashboarding product metrics',
      ],
    },
  ],
  'data-science': [
    {
      id: 'data-science-ml-fundamentals',
      label: 'Machine Learning Fundamentals',
      iconKey: 'brain',
      blurb:
        'AI vs ML vs Deep Learning vs GenAI distinctions, supervised vs unsupervised vs semi-supervised vs reinforcement learning, and regression vs classification problems.',
      rubricFocus: [
        'AI vs ML vs Deep Learning vs GenAI distinctions',
        'Supervised vs unsupervised vs semi-supervised vs reinforcement learning',
        'Regression vs classification problems',
        'Features vs target variable',
      ],
      subtopics: [
        'AI vs ML vs Deep Learning vs GenAI distinctions',
        'Supervised vs unsupervised vs semi-supervised vs reinforcement learning',
        'Regression vs classification problems',
        'Features vs target variable',
        'Mapping a business problem to an ML problem',
        'End-to-end ML workflow (data to prediction to deployment)',
        'Parametric vs non-parametric models',
        'Bias-variance tradeoff (conceptual)',
        'Train/validation/test split & common splitting pitfalls',
        'Data leakage (sources & prevention)',
        'Handling missing values (imputation strategies, SimpleImputer)',
        'Outlier handling (IQR, z-score, capping/flooring/removal)',
        'Encoding categorical variables (label encoding, one-hot encoding, ordinal, target encoding)',
        'Feature scaling (standardization, normalization, MinMaxScaler, StandardScaler, RobustScaler)',
        'Feature engineering patterns (interaction terms, binning, polynomial features, date/count/ratio features)',
        'Feature selection (filter, wrapper, embedded methods, mutual information)',
        'scikit-learn Pipeline & ColumnTransformer',
        'Curse of dimensionality',
      ],
    },
    {
      id: 'data-science-supervised-ml',
      label: 'Supervised Machine Learning',
      iconKey: 'brain',
      blurb:
        'Linear regression assumptions & model structure, fitting with scikit-learn (fit, predict), and interpreting coefficients & intercept.',
      rubricFocus: [
        'Linear regression assumptions & model structure',
        'Fitting with scikit-learn',
        'Interpreting coefficients & intercept',
        'Residual analysis',
      ],
      subtopics: [
        'Linear regression assumptions & model structure',
        'Fitting with scikit-learn (fit, predict)',
        'Interpreting coefficients & intercept',
        'Residual analysis',
        'Evaluation metrics (MAE, MSE, RMSE, R-squared, Adjusted R-squared)',
        'Regularization (Ridge/L2, Lasso/L1, ElasticNet)',
        'Logistic regression & the sigmoid function',
        'Predicted probability & decision threshold',
        'Multiclass logistic regression (one-vs-rest, softmax)',
        'Confusion matrix (TP, TN, FP, FN)',
        'Accuracy',
        'precision',
        'recall & F1-score',
        'Precision-recall tradeoff & choosing the right metric',
        'ROC curve & AUC',
        'Threshold tuning',
        'Decision trees (Gini impurity, information gain/entropy, max_depth, min_samples_leaf/split, pruning)',
        'Overfitting vs underfitting recognition',
        'k-Nearest Neighbors (KNN)',
        'Naive Bayes (Gaussian, Multinomial)',
        'Support Vector Machines (linear & kernel SVM, margin intuition)',
        'Bagging vs boosting intuition',
        'Random Forests (feature importance, out-of-bag error)',
        'Gradient Boosting (sequential error correction)',
        'XGBoost',
        'LightGBM & CatBoost',
        'Stacking & voting classifiers',
        'Comparing single-model vs ensemble performance',
      ],
    },
    {
      id: 'data-science-unsupervised-ml-time-series',
      label: 'ML - Unsupervised & Time Series',
      iconKey: 'network',
      blurb:
        'k-fold & Stratified k-fold cross-validation, GridSearchCV & RandomizedSearchCV hyperparameter tuning, and bayesian hyperparameter optimization (Optuna).',
      rubricFocus: [
        'k-fold & Stratified k-fold cross-validation',
        'GridSearchCV & RandomizedSearchCV hyperparameter tuning',
        'Bayesian hyperparameter optimization',
        'Class imbalance diagnosis',
      ],
      subtopics: [
        'k-fold & Stratified k-fold cross-validation',
        'GridSearchCV & RandomizedSearchCV hyperparameter tuning',
        'Bayesian hyperparameter optimization (Optuna)',
        'Class imbalance diagnosis',
        'Resampling (oversampling, undersampling, SMOTE)',
        'Class weighting',
        'Metrics for imbalanced problems (precision, recall, F1, AUC-PR)',
        'Learning curves & diagnosing bias vs variance',
        'Model interpretability (feature importance, SHAP, LIME)',
        'Model saving & serialization (joblib, pickle)',
        'Communicating model results & metrics to non-technical stakeholders',
        'K-Means clustering (centroids, elbow method, silhouette score)',
        'Hierarchical clustering (dendrograms)',
        'DBSCAN (density-based clustering)',
        'Gaussian Mixture Models',
        'Dimensionality reduction (PCA, t-SNE, UMAP)',
        'Association rule mining (Apriori, market basket analysis)',
        'Recommendation systems (collaborative filtering, content-based filtering)',
        'Distance metrics (Euclidean, Manhattan, cosine)',
        'Anomaly types (point, contextual, collective)',
        'Statistical methods (IQR, z-score thresholds)',
        'Isolation Forest',
        'One-Class SVM',
        'Autoencoder-based anomaly detection',
        'Evaluating anomaly detectors without clean labels',
        'Trend',
        'seasonality & noise decomposition',
        'Stationarity & differencing',
        'Moving averages & exponential smoothing',
        'ARIMA/SARIMA models',
        'Prophet',
        'Forecast evaluation (MAPE, RMSE)',
        'Time series cross-validation',
        'Bias in hiring/lending/healthcare models',
        'Fairness metrics & checks',
        'Model explainability for stakeholders',
        'Privacy-preserving ML (basics)',
        'Responsible ML practice & governance',
      ],
    },
    {
      id: 'data-science-deep-learning-foundations',
      label: 'Deep Learning - Foundations',
      iconKey: 'network',
      blurb:
        'Classical ML vs deep learning, artificial neuron & network layer structure, and activation functions (ReLU, sigmoid, tanh, softmax, leaky ReLU, GELU).',
      rubricFocus: [
        'Classical ML vs deep learning',
        'Artificial neuron & network layer structure',
        'Activation functions',
        'Forward pass',
      ],
      subtopics: [
        'Classical ML vs deep learning',
        'Artificial neuron & network layer structure',
        'Activation functions (ReLU, sigmoid, tanh, softmax, leaky ReLU, GELU)',
        'Forward pass',
        'Loss functions (MSE, cross-entropy, categorical vs binary)',
        'Backpropagation intuition & chain rule',
        'Gradient descent & weight updates',
        'Batch size & epoch concepts',
        'Frameworks (PyTorch, TensorFlow/Keras basics)',
        'Tensors (creation, operations, shape, device placement/GPU)',
        'Optimizers (SGD, Momentum, RMSProp, Adam)',
        'Learning rate schedules & warmup',
        'Dropout',
        'L1/L2 regularization & weight decay',
        'Batch normalization & layer normalization',
        'Early stopping',
        'Vanishing & exploding gradients',
        'Data augmentation & label smoothing',
        'Building & training an MLP classifier',
        'Reading & diagnosing loss curves',
        'Convolutional layers & filters/kernels',
        'Pooling layers (max, average)',
        'Building a CNN for image classification',
        'Classic architectures (LeNet, AlexNet, VGG, ResNet, Inception, EfficientNet)',
        'Transfer learning & fine-tuning pretrained models',
        'Freezing vs unfreezing layers',
        'Evaluating accuracy & misclassifications',
      ],
    },
    {
      id: 'data-science-deep-learning-advanced',
      label: 'Deep Learning - Advanced',
      iconKey: 'network',
      blurb:
        'Why feedforward nets struggle with sequences, RNNs (hidden state, carrying information forward), and LSTM (gates, memory cell, vanishing gradients).',
      rubricFocus: [
        'Why feedforward nets struggle with sequences',
        'RNNs',
        'LSTM',
        'GRU',
      ],
      subtopics: [
        'Why feedforward nets struggle with sequences',
        'RNNs (hidden state, carrying information forward)',
        'LSTM (gates, memory cell, vanishing gradients)',
        'GRU',
        'Bidirectional RNNs',
        'Sequence-to-sequence models & encoder-decoder architecture',
        'Building an LSTM forecaster',
        'Self-attention & scaled dot-product attention',
        'Multi-head attention',
        'Positional encoding',
        'Encoder vs decoder vs encoder-decoder architectures',
        'Feed-forward layers & residual connections',
        'Layer normalization in transformers',
        'Tokens & prompt-to-output flow',
        'Autoencoders & Variational Autoencoders (VAEs)',
        'GANs (generator vs discriminator, adversarial training loop)',
        'GAN training problems (mode collapse, instability)',
        'Diffusion models (forward noising, reverse denoising, UNet)',
        'Using pretrained generative models (Stable Diffusion)',
        'Evaluating generated samples (FID intuition)',
        'Model checkpoints (saving/loading)',
        'Mixed-precision training',
        'Model quantization & pruning',
        'Knowledge distillation',
        'ONNX & cross-framework export',
        'Benchmarking latency',
        'size & accuracy tradeoffs',
        'Choosing an architecture for a stated product constraint',
      ],
    },
    {
      id: 'data-science-math-for-ml',
      label: 'Math for ML',
      iconKey: 'sigma',
      blurb:
        'Scalars, vectors & vector operations (addition, scalar multiplication), and vector magnitude & unit vectors.',
      rubricFocus: [
        'Scalars',
        'vectors & vector operations',
        'Vector magnitude & unit vectors',
        'Dot product & angle between vectors',
      ],
      subtopics: [
        'Scalars',
        'vectors & vector operations (addition, scalar multiplication)',
        'Vector magnitude & unit vectors',
        'Dot product & angle between vectors',
        'Cosine similarity',
        'Matrices & matrix multiplication',
        'Representing datasets as feature matrices',
        'Identity',
        'transpose & inverse matrices',
        'Eigenvectors & eigenvalues',
        'Matrices as transformations (rotation, scaling, reshaping)',
        'Principal Component Analysis (PCA) intuition',
        'Vector spaces',
        'basis & dimensions',
        'Coordinate geometry (Cartesian plane, slope as rise/run)',
        'Descriptive statistics (mean, median, mode, variance, standard deviation)',
        'Probability rules (classical, empirical, subjective, addition & multiplication rules)',
        "Conditional probability & Bayes' theorem",
        'Probability distributions (PDF vs CDF, normal, binomial, Poisson, exponential)',
        'Sampling & the Central Limit Theorem',
        'Covariance & correlation',
        'Confidence intervals & hypothesis testing recap',
        'Maximum Likelihood Estimation (MLE)',
        'Entropy',
        'cross-entropy & KL divergence',
        'Perplexity (as used in language model evaluation)',
        'Functions & plotting (y=x^2, y=x^3)',
        'Average rate of change & derivative intuition',
        'Derivative as slope of a curve',
        'Basic derivative rules (power, constant, sum)',
        'Partial derivatives & gradients',
        'Chain rule',
        'Finding minima/maxima (dy/dx = 0)',
        'Gradient descent (batch, stochastic, mini-batch)',
        'Convex vs non-convex optimization',
        'Learning rate & convergence behavior',
        "Second-order methods (conceptual: Newton's method)",
        'Set theory (union, intersection, complement, subsets)',
        'Functions (domain, codomain, range)',
        'Boolean logic & truth tables',
        'Number systems (binary representation)',
        'Combinatorics basics (permutations & combinations) for probability',
        "De Morgan's laws",
        'Bias-variance decomposition',
        'Information-theoretic feature selection (mutual information vs correlation)',
        'Model calibration (reliability diagrams, Brier score, Platt scaling)',
        'Multi-class & imbalanced calibration',
        'Markov chains (predicting the next state)',
      ],
    },
    {
      id: 'data-science-nlp',
      label: 'NLP',
      iconKey: 'chat-circle',
      blurb:
        'Tokenization (word, subword, sentence), stop-word removal, and stemming & lemmatization.',
      rubricFocus: [
        'Tokenization',
        'Stop-word removal',
        'Stemming & lemmatization',
        'Bag-of-Words & TF-IDF',
      ],
      subtopics: [
        'Tokenization (word, subword, sentence)',
        'Stop-word removal',
        'Stemming & lemmatization',
        'Bag-of-Words & TF-IDF',
        'N-grams',
        'Text normalization (lowercasing, punctuation/special character handling)',
        'Part-of-speech (POS) tagging',
        'Named Entity Recognition (NER)',
        'One-hot encoding vs dense embeddings',
        'Word2Vec (CBOW & Skip-gram)',
        'GloVe',
        'FastText',
        'Pretrained embeddings vs training your own',
        'Sentence embeddings (sentence-transformers)',
        'Cosine similarity for semantic comparison',
        'Semantic search vs keyword search',
        'Embedding visualization',
        'Text classification (spam detection, sentiment analysis)',
        'Sequence labeling (NER, POS tagging)',
        'TF-IDF + classifier pipelines',
        'RNN/LSTM-based text models',
        'Text summarization (extractive vs abstractive)',
        'Machine translation basics',
        'Topic modeling (LDA)',
        'Attention mechanism intuition',
        'Transformers vs RNNs',
        'Pretrained transformer models via Hugging Face',
        'Fine-tuning transformers for a downstream task',
        'BERT-style vs GPT-style architectures (encoder-only vs decoder-only vs encoder-decoder)',
        'Real-world applications (translation, search, chatbots)',
      ],
    },
    {
      id: 'data-science-computer-vision',
      label: 'Computer Vision',
      iconKey: 'eye',
      blurb:
        'Digital image representation (pixels, channels, RGB vs grayscale), image preprocessing (resizing, normalization, color space conversion), and basic OpenCV operations (reading/writing images, filtering, edge detection).',
      rubricFocus: [
        'Digital image representation',
        'Image preprocessing',
        'Basic OpenCV operations',
        'Image augmentation',
      ],
      subtopics: [
        'Digital image representation (pixels, channels, RGB vs grayscale)',
        'Image preprocessing (resizing, normalization, color space conversion)',
        'Basic OpenCV operations (reading/writing images, filtering, edge detection)',
        'Image augmentation (flips, rotation, crop, color jitter)',
        'CNN-based image classifiers',
        'Transfer learning with pretrained backbones (ResNet, EfficientNet, MobileNet)',
        'Data augmentation strategies for small datasets',
        'Evaluating classifiers (accuracy, confusion matrix, top-k accuracy)',
        'Object detection vs classification vs localization',
        'Bounding boxes & IoU (Intersection over Union)',
        'Non-Maximum Suppression (NMS)',
        'One-stage detectors (YOLO family, SSD)',
        'Two-stage detectors (R-CNN, Faster R-CNN)',
        'Semantic segmentation vs instance segmentation (U-Net, Mask R-CNN)',
        'Running pretrained detection/segmentation models',
        'Vision Transformer (ViT) architecture',
        'CNNs vs ViTs tradeoffs',
        'Self-supervised vision pretraining (contrastive learning basics)',
        'Multi-modal vision-language models (CLIP)',
        'Applied CV use cases (visual search, OCR, face recognition/Face ID, product tagging)',
      ],
    },
    {
      id: 'data-science-mlops',
      label: 'MLOps',
      iconKey: 'cloud',
      blurb:
        'ML lifecycle (data to training to deployment to monitoring), reproducibility (environment pinning, requirements.txt vs lockfiles), and notebook-to-pipeline conversion.',
      rubricFocus: [
        'ML lifecycle',
        'Reproducibility',
        'Notebook-to-pipeline conversion',
        'Version control for ML',
      ],
      subtopics: [
        'ML lifecycle (data to training to deployment to monitoring)',
        'Reproducibility (environment pinning, requirements.txt vs lockfiles)',
        'Notebook-to-pipeline conversion',
        'Version control for ML (Git workflow, branching strategy, PR structure)',
        'Data versioning (DVC)',
        'Experiment tracking tools (MLflow, Weights & Biases)',
        'Tagging & querying runs at scale',
        'Reproducing a specific run',
        'Reproducibility checklist before declaring a model final',
        'Team-ready documentation standards',
        'Serving a model via FastAPI/Flask',
        'Input validation & endpoint testing',
        'Containerization with Docker (writing a Dockerfile, build & run locally, debugging build failures)',
        'Cloud deployment of containerized services',
        'Managing secrets & environment variables in production',
        'Batch vs real-time (online) inference',
        'Model registries',
        'Streamlit/Gradio for quick demo apps',
        'Structured logging',
        'Operational metrics (volume, latency, error rate)',
        'Alerting on thresholds',
        'Reconstructing failed requests from logs',
        'Model & data drift detection',
        'CI/CD pipelines for ML (automated testing, retraining triggers)',
        'Rolling back a deployment',
        'A/B testing models in production',
        'Cost/latency/quality tradeoffs at scale',
      ],
    },
  ],
  'applied-ai': [
    {
      id: 'applied-ai-llm-foundations',
      label: 'LLMs - Foundations, Architecture & Training',
      iconKey: 'brain',
      blurb:
        'How LLMs differ from classical ML/DL, transformer recap (self-attention, positional encoding, encoder/decoder/decoder-only), and tokens & tokenization (BPE, WordPiece, SentencePiece).',
      rubricFocus: [
        'How LLMs differ from classical ML/DL',
        'Transformer recap',
        'Tokens & tokenization',
        'Vocabulary size & token limits',
      ],
      subtopics: [
        'How LLMs differ from classical ML/DL',
        'Transformer recap (self-attention, positional encoding, encoder/decoder/decoder-only)',
        'Tokens & tokenization (BPE, WordPiece, SentencePiece)',
        'Vocabulary size & token limits',
        'Model families overview (GPT, Claude, Gemini, Llama, Mistral)',
        'Proprietary vs open-source model ecosystems',
        'Model scaling laws (conceptual)',
        'Emergent abilities at scale',
        'Pretraining (next-token prediction on large corpora)',
        'Instruction fine-tuning',
        'Supervised Fine-Tuning (SFT) & instruction-response pairs',
        'RLHF (reward modeling & reinforcement learning from human feedback)',
        'DPO (Direct Preference Optimization) as an RLHF alternative',
        'Why training stages matter for behavior',
      ],
    },
    {
      id: 'applied-ai-prompt-engineering',
      label: 'LLMs - Prompt Engineering, Context & Inference',
      iconKey: 'sparkle',
      blurb:
        'Anatomy of a prompt (task, context, constraints, format), zero-shot vs few-shot prompting, and role/system prompting.',
      rubricFocus: [
        'Anatomy of a prompt',
        'Zero-shot vs few-shot prompting',
        'Role/system prompting',
        'Chain-of-thought prompting',
      ],
      subtopics: [
        'Anatomy of a prompt (task, context, constraints, format)',
        'Zero-shot vs few-shot prompting',
        'Role/system prompting',
        'Chain-of-thought prompting',
        'Self-consistency & tree-of-thought (advanced reasoning prompting)',
        'Structured prompting templates',
        'Iterative prompt refinement & failure analysis',
        'Prompt injection awareness (basic)',
        'Reusable prompt libraries/workflows',
        'Context window size & constraints',
        'Temperature & top-p (nucleus) sampling',
        'Top-k sampling',
        'Frequency & presence penalties',
        'Token usage',
        'cost & latency tradeoffs',
        'Streaming responses',
        'Multi-turn conversation state & memory across turns',
        'Calling LLM APIs programmatically (OpenAI/Anthropic/OpenRouter SDKs, auth, request/response structure, error handling & rate limiting)',
        'Hugging Face Hub for open-source models',
      ],
    },
    {
      id: 'applied-ai-llm-fine-tuning',
      label: 'LLMs - Fine-Tuning, Structured Outputs & Evaluation',
      iconKey: 'sparkle',
      blurb:
        'Full fine-tuning vs parameter-efficient fine-tuning (PEFT), LoRA (Low-Rank Adaptation) intuition & implementation, and QLoRA (quantized LoRA).',
      rubricFocus: [
        'Full fine-tuning vs parameter-efficient fine-tuning',
        'LoRA (Low-Rank Adaptation) intuition & implementation',
        'QLoRA',
        'Comparing SFT vs LoRA vs QLoRA on cost/performance',
      ],
      subtopics: [
        'Full fine-tuning vs parameter-efficient fine-tuning (PEFT)',
        'LoRA (Low-Rank Adaptation) intuition & implementation',
        'QLoRA (quantized LoRA)',
        'Comparing SFT vs LoRA vs QLoRA on cost/performance',
        'Preparing an instruction-tuning dataset',
        'Fine-tuning vs prompting vs RAG decision framework (cost, data availability, change frequency)',
        'Running & evaluating a fine-tuning job',
        'JSON schema design for structured LLM outputs',
        'Output parsing & validation (Pydantic, instructor library)',
        'Function calling / tool calling APIs',
        'Designing tool schemas for reliable invocation',
        'Handling malformed or partial structured outputs',
        'Perplexity as a language-model metric',
        'Standard benchmarks (MMLU, HumanEval, HELM - awareness level)',
        'Human evaluation vs automated evaluation',
        'LLM-as-judge evaluation pattern',
        'Hallucination detection & measurement',
        'Building a custom evaluation harness for an application',
        'Regression testing after a prompt/model change',
      ],
    },
    {
      id: 'applied-ai-rag-foundations',
      label: 'RAG - Foundations, Vector Databases & Pipeline',
      iconKey: 'database',
      blurb:
        'Why retrieval augments a fixed context window, loading documents (PDF, text, HTML, structured data), and chunking strategies (fixed-size vs semantic vs recursive character splitting).',
      rubricFocus: [
        'Why retrieval augments a fixed context window',
        'Loading documents',
        'Chunking strategies',
        'Choosing chunk size & overlap',
      ],
      subtopics: [
        'Why retrieval augments a fixed context window',
        'Loading documents (PDF, text, HTML, structured data)',
        'Chunking strategies (fixed-size vs semantic vs recursive character splitting)',
        'Choosing chunk size & overlap',
        'Generating embeddings',
        'Comparing embedding models',
        'Cosine similarity & nearest-neighbor search',
        'Vector database landscape (FAISS, Chroma, Pinecone, Weaviate, Milvus)',
        'Indexing strategies (flat, IVF, HNSW)',
        'Top-k retrieval & similarity score thresholds',
        'Metadata filtering',
        'Hybrid search (keyword/BM25 + vector)',
        'Reranking retrieved results (cross-encoders)',
        'Evaluating retrieval quality (context recall/precision)',
        'MMR (Maximal Marginal Relevance) for diverse retrieval results',
        'Chunk -> embed -> retrieve -> generate pipeline',
        'Connecting retrieval output to LLM generation (context injection)',
        'Prompt templates for grounded generation',
        'Checking answer grounding / source attribution',
        'Tuning top-k & score thresholds',
        'Multi-document & multi-hop retrieval',
        'Conversational RAG (retrieval with chat history)',
      ],
    },
    {
      id: 'applied-ai-rag-advanced',
      label: 'RAG - Advanced & Agentic RAG',
      iconKey: 'network',
      blurb:
        'Query rewriting & expansion, self-querying retrievers, and agentic RAG (retriever exposed as a tool to an agent).',
      rubricFocus: [
        'Query rewriting & expansion',
        'Self-querying retrievers',
        'Agentic RAG',
        'GraphRAG',
      ],
      subtopics: [
        'Query rewriting & expansion',
        'Self-querying retrievers',
        'Agentic RAG (retriever exposed as a tool to an agent)',
        'GraphRAG (knowledge-graph-augmented retrieval)',
        'RAG evaluation frameworks (RAGAS: faithfulness, answer relevance, context recall)',
        'Common failure modes (empty context, wrong chunks, retrieval noise) & mitigation',
        'Hallucination reduction via grounding & verification',
      ],
    },
    {
      id: 'applied-ai-llmops',
      label: 'LLMOps - Serving, Guardrails, Cost & Reliability',
      iconKey: 'cloud',
      blurb:
        "Why serving one request at a time doesn't scale, batching requests for throughput vs latency, and KV-caching for autoregressive generation.",
      rubricFocus: [
        "Why serving one request at a time doesn't scale",
        'Batching requests for throughput vs latency',
        'KV-caching for autoregressive generation',
        'Speculative decoding',
      ],
      subtopics: [
        "Why serving one request at a time doesn't scale",
        'Batching requests for throughput vs latency',
        'KV-caching for autoregressive generation',
        'Speculative decoding',
        'Quantization for inference (INT8/INT4)',
        'Model distillation for cheaper serving',
        'Choosing a serving strategy for a stated traffic pattern',
        'Self-hosted vs API-based inference tradeoffs',
        'Prompt versioning',
        'Automated evaluation harness & catching regressions',
        'Input validation for LLM applications',
        'Output guardrails (content filtering, schema enforcement)',
        'Jailbreak & prompt-injection defenses',
        'Human-in-the-loop review checkpoints',
        'Rate limiting & retry/backoff strategies',
        'Cost-per-request & cost-per-resolved-task tracking',
        'Latency budgets & p50/p95/p99 monitoring',
        'LLM production failure modes (hallucination, drift, cost blowouts)',
        'Observability (structured logging, tracing multi-step LLM calls)',
        'Alerting on quality/cost/latency thresholds',
        'User feedback loops (capturing corrections, routing to retraining/prompt improvement)',
        'Avoiding feedback loops that reinforce bias',
        'PII redaction & data privacy in prompts/logs',
      ],
    },
    {
      id: 'applied-ai-ai-agentics-architecture',
      label: 'AI Agentics - Architecture, Frameworks & Orchestration',
      iconKey: 'robot',
      blurb:
        'Agent vs single LLM call, core agent components (planning, reasoning, tools, memory), and ReAct pattern (reasoning + acting).',
      rubricFocus: [
        'Agent vs single LLM call',
        'Core agent components',
        'ReAct pattern',
        'Defining tools/functions for an agent',
      ],
      subtopics: [
        'Agent vs single LLM call',
        'Core agent components (planning, reasoning, tools, memory)',
        'ReAct pattern (reasoning + acting)',
        'Defining tools/functions for an agent',
        'Building a single-tool and multi-tool agent',
        'Tracing & debugging agent reasoning steps',
        'Common tool types (web search, code execution, database/API access)',
        'LangChain (Tool, AgentExecutor, chains)',
        'LangGraph (StateGraph, nodes, edges, conditional routing, compile())',
        'CrewAI (roles, tasks, sequential/hierarchical crews)',
        'AutoGen (conversable agents)',
        'Choosing a framework for a given orchestration need (single-agent vs graph vs role-based crew)',
        'Splitting tasks across specialized agents',
        'Orchestrator-worker architecture (lead agent delegating to workers)',
        'Agent handoffs & shared memory/context across handoffs',
        'Multi-agent consensus (voting, weighted consensus, arbitration)',
        'Conflict resolution between disagreeing agents',
        'Aggregating & reconciling worker outputs',
      ],
    },
    {
      id: 'applied-ai-ai-agentics-safety',
      label: 'AI Agentics - Memory, Safety & Evaluation',
      iconKey: 'robot',
      blurb:
        'Short-term context vs persistent long-term memory, implementing a memory store an agent can read/write, and retrieval-augmented agent memory.',
      rubricFocus: [
        'Short-term context vs persistent long-term memory',
        'Implementing a memory store an agent can read/write',
        'Retrieval-augmented agent memory',
        'Long-running autonomous workflows tracking progress across steps',
      ],
      subtopics: [
        'Short-term context vs persistent long-term memory',
        'Implementing a memory store an agent can read/write',
        'Retrieval-augmented agent memory',
        'Long-running autonomous workflows tracking progress across steps',
        'Stopping conditions & human checkpoints for autonomous runs',
        'Idempotent tool design',
        'Prompt injection attacks against tool-using agents',
        'Guardrails for agent inputs & outputs',
        'Sandboxing & rate-limiting risky tool calls',
        'Human-in-the-loop checkpoints for high-stakes actions',
        'Unit-testing individual agent tools',
        'Simulating multi-turn conversations to test agent behavior',
        'Tracking task-success rate & tool-call accuracy',
        'Hallucination rate & cost-per-resolved-task for agents',
        'Regression testing an agent after a prompt/tool change',
        'Judging when NOT to automate a task with an agent',
      ],
    },
    {
      id: 'applied-ai-genai-landscape',
      label: 'GenAI - Landscape, Tools & Application Patterns',
      iconKey: 'sparkle',
      blurb:
        'AI vs ML vs GenAI definitions & positioning, modalities of generative AI (text, image, audio, video, code), and foundation models overview.',
      rubricFocus: [
        'AI vs ML vs GenAI definitions & positioning',
        'Modalities of generative AI',
        'Foundation models overview',
        'Where GenAI fits into an existing analytics/business workflow',
      ],
      subtopics: [
        'AI vs ML vs GenAI definitions & positioning',
        'Modalities of generative AI (text, image, audio, video, code)',
        'Foundation models overview',
        'Where GenAI fits into an existing analytics/business workflow',
        'Open-source vs proprietary GenAI tools',
        'Using ChatGPT/Claude/Gemini for drafting',
        'summarizing & rewriting',
        'GenAI for code generation & debugging assistance',
        'Custom GPTs / Claude Projects / Gemini Gems for recurring tasks',
        'Prompt-check-improve iteration pattern',
        'Generating structured outputs (tables, lists, reports) via prompts',
        'Text-to-image tools (Midjourney, DALL-E, Stable Diffusion) & prompt/guidance-scale control',
        'Image editing & inpainting with GenAI',
        'Text-to-speech & voice cloning tools',
        'Text-to-video & video editing GenAI tools',
        'Ethical/IP considerations for generated media',
        'GenAI as a co-pilot for analysis & pre-processing',
        'Multi-step GenAI-supported workflows',
        'Interpreting & validating GenAI outputs (spotting low-quality/incorrect outputs)',
        'Building a personal/team prompt library',
        'Critiquing & improving AI-generated drafts',
        'Fact-checking & editing AI output for accuracy and tone',
      ],
    },
    {
      id: 'applied-ai-ai-strategy-governance',
      label: 'Applied AI - Strategy, Governance & Use Cases',
      iconKey: 'briefcase',
      blurb:
        'Identifying high-value AI use cases for a business function, building a business case for AI adoption (cost, ROI, risk), and AI vs traditional analytics spectrum.',
      rubricFocus: [
        'Identifying high-value AI use cases for a business function',
        'Building a business case for AI adoption',
        'AI vs traditional analytics spectrum',
        'Digital transformation & change leadership with AI',
      ],
      subtopics: [
        'Identifying high-value AI use cases for a business function',
        'Building a business case for AI adoption (cost, ROI, risk)',
        'AI vs traditional analytics spectrum',
        'Digital transformation & change leadership with AI',
        'Digital business models & platforms powered by data/AI',
        'Build vs buy vs fine-tune vs prompt decision framework',
        'Data & AI ecosystem landscape (structured vs semi-structured vs unstructured data; where analysts/AI practitioners fit)',
        'AI as a source of competitive advantage',
        'Adopting new AI-driven operating models',
        'AI governance & accountability frameworks',
        'Data privacy & compliance considerations (PII handling)',
        'Bias & fairness in AI systems',
        'Explainability & interpretability for stakeholders',
        'Responsible AI adoption checklists',
        'Human oversight & escalation policies',
        'AI in sales & marketing (personalization, lead scoring, content generation)',
        'AI in customer support (chatbots, ticket triage, summarization)',
        'AI in operations & supply chain (demand forecasting, anomaly detection)',
        'AI in finance (fraud detection, risk scoring)',
        'AI in HR & recruiting (screening assistance, skills matching)',
        'AI in product & engineering (copiloting, code review, testing)',
        'Scoping an AI feature/product (problem framing, feasibility, data availability)',
        'Defining success metrics for an AI feature',
        'Change management & user adoption for AI tools',
        'Vendor/tool evaluation for AI capabilities',
        'Measuring AI ROI post-deployment',
        'Continuous improvement based on user feedback',
      ],
    },
  ],
  general: [
    {
      id: 'behavioral-hr',
      label: 'Behavioral / HR Round',
      iconKey: 'chat-circle',
      blurb: 'Communication, teamwork, and past-experience questions.',
      rubricFocus: [
        'Clarity of communication',
        'Structured storytelling',
        'Self-awareness',
      ],
      subtopics: [],
    },
  ],
}

export function getCatalogTopicsForDomains(
  domains: Array<InterviewDomain>,
): Array<InterviewTopic> {
  const seen = new Set<string>()
  const topics: Array<InterviewTopic> = []
  for (const domain of domains) {
    for (const topic of INTERVIEW_TOPIC_CATALOG[domain]) {
      if (seen.has(topic.id)) continue
      seen.add(topic.id)
      topics.push({ ...topic, domain })
    }
  }
  return topics
}

export function findCatalogTopicById(
  topicId: string,
): CatalogTopic | undefined {
  for (const topics of Object.values(INTERVIEW_TOPIC_CATALOG)) {
    const found = topics.find((topic) => topic.id === topicId)
    if (found) return found
  }
  return undefined
}

export function findCatalogTopicDomainById(
  topicId: string,
): InterviewDomain | undefined {
  for (const [domain, topics] of Object.entries(INTERVIEW_TOPIC_CATALOG)) {
    if (topics.some((topic) => topic.id === topicId)) {
      return domain as InterviewDomain
    }
  }
  return undefined
}
