import {
  Atom,
  Brain,
  Briefcase,
  ChartBar,
  ChartLine,
  ChartPie,
  ChatCircle,
  Cloud,
  Code,
  CurrencyDollar,
  Cube,
  Database,
  EnvelopeSimple,
  Eye,
  GitBranch,
  Handshake,
  Layout,
  Lightbulb,
  ListChecks,
  MagnifyingGlass,
  Megaphone,
  Network,
  Palette,
  Robot,
  Rocket,
  ShieldCheck,
  ShoppingCart,
  Sigma,
  Sparkle,
  Stack,
  Table,
  Target,
  Terminal,
  Wrench,
  BookOpen,
  type IconProps,
} from '@phosphor-icons/react'
import type { ComponentType } from 'react'

const TOPIC_ICONS: Record<string, ComponentType<IconProps>> = {
  sigma: Sigma,
  network: Network,
  'layout-template': Layout,
  code: Code,
  database: Database,
  cube: Cube,
  brain: Brain,
  sparkle: Sparkle,
  lightbulb: Lightbulb,
  'chart-line': ChartLine,
  briefcase: Briefcase,
  'list-checks': ListChecks,
  'chat-circle': ChatCircle,
  atom: Atom,
  palette: Palette,
  'git-branch': GitBranch,
  wrench: Wrench,
  terminal: Terminal,
  'shield-check': ShieldCheck,
  cloud: Cloud,
  stack: Stack,
  megaphone: Megaphone,
  'magnifying-glass': MagnifyingGlass,
  'currency-dollar': CurrencyDollar,
  'envelope-simple': EnvelopeSimple,
  'shopping-cart': ShoppingCart,
  target: Target,
  rocket: Rocket,
  handshake: Handshake,
  'chart-bar': ChartBar,
  table: Table,
  'chart-pie': ChartPie,
  eye: Eye,
  robot: Robot,
}

const FALLBACK_ICON: ComponentType<IconProps> = BookOpen

export function getTopicIcon(iconKey: string): ComponentType<IconProps> {
  return TOPIC_ICONS[iconKey] ?? FALLBACK_ICON
}
