/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedLayoutRouteRouteImport } from './routes/(protected)/_layout/route'
import { Route as protectedZoomIndexRouteImport } from './routes/(protected)/zoom/index'
import { Route as protectedLayoutIndexRouteImport } from './routes/(protected)/_layout/index'
import { Route as authSwitchAccountIndexRouteImport } from './routes/(auth)/switch-account/index'
import { Route as authSigninIndexRouteImport } from './routes/(auth)/signin/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as ApiLearnBatchesRouteImport } from './routes/api/learn/batches'
import { Route as ApiLearnBatchDataRouteImport } from './routes/api/learn/batch-data'
import { Route as ApiDashboardScheduleRouteImport } from './routes/api/dashboard/schedule'
import { Route as ApiDashboardProductUpdatesRouteImport } from './routes/api/dashboard/product-updates'
import { Route as ApiDashboardPendingTasksRouteImport } from './routes/api/dashboard/pending-tasks'
import { Route as ApiDashboardBannersRouteImport } from './routes/api/dashboard/banners'
import { Route as ApiDashboardAnnouncementsRouteImport } from './routes/api/dashboard/announcements'
import { Route as ApiDashboardActionBannersRouteImport } from './routes/api/dashboard/action-banners'
import { Route as authV2ResetPasswordRouteImport } from './routes/(auth)/v2/reset-password'
import { Route as authV2MeRouteImport } from './routes/(auth)/v2/me'
import { Route as authV2ForgotPasswordRouteImport } from './routes/(auth)/v2/forgot-password'
import { Route as protectedLayoutMasaiverseRouteRouteImport } from './routes/(protected)/_layout/masaiverse/route'
import { Route as protectedLayoutMasaiverseIndexRouteImport } from './routes/(protected)/_layout/masaiverse/index'
import { Route as protectedLayoutLearnIndexRouteImport } from './routes/(protected)/_layout/learn/index'
import { Route as authV2LoginIndexRouteImport } from './routes/(auth)/v2/login/index'
import { Route as authResetPasswordTokenIndexRouteImport } from './routes/(auth)/reset-password.$token/index'
import { Route as ApiLearnSubmissionsSubmissionIdRouteImport } from './routes/api/learn/submissions/$submissionId'
import { Route as ApiLearnResourcesResourceIdRouteImport } from './routes/api/learn/resources/$resourceId'
import { Route as ApiLearnLecturesLectureIdRouteImport } from './routes/api/learn/lectures/$lectureId'
import { Route as ApiLearnAssignmentsAssignmentIdRouteImport } from './routes/api/learn/assignments/$assignmentId'
import { Route as ApiLearnAiTutorLimitRouteImport } from './routes/api/learn/ai-tutor/limit'
import { Route as ApiLearnAiTutorEndRouteImport } from './routes/api/learn/ai-tutor/end'
import { Route as authV2LoginVerifyOtpRouteImport } from './routes/(auth)/v2/login/verify-otp'
import { Route as authV2LoginRequestOtpRouteImport } from './routes/(auth)/v2/login/request-otp'
import { Route as authV2AuthUseAccountRouteImport } from './routes/(auth)/v2/auth/use-account'
import { Route as authV2AuthLinkedAccountsRouteImport } from './routes/(auth)/v2/auth/linked-accounts'
import { Route as protectedLayoutResourcesResourceIdRouteRouteImport } from './routes/(protected)/_layout/resources_/$resourceId/route'
import { Route as protectedLayoutLecturesLectureIdRouteRouteImport } from './routes/(protected)/_layout/lectures_/$lectureId/route'
import { Route as protectedLayoutAssignmentsAssignmentIdRouteRouteImport } from './routes/(protected)/_layout/assignments_/$assignmentId/route'
import { Route as ApiLearnSubmissionsSubmissionIdViewOnPlatformRouteImport } from './routes/api/learn/submissions/$submissionId/view-on-platform'
import { Route as ApiLearnAssignmentsAssignmentIdSubmissionsRouteImport } from './routes/api/learn/assignments/$assignmentId/submissions'
import { Route as ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRouteImport } from './routes/api/learn/assignments/$assignmentId/assess-platform-url'
import { Route as ApiLearnAiTutorLectureIdTranscriptRouteImport } from './routes/api/learn/ai-tutor/$lectureId/transcript'
import { Route as ApiLearnAiTutorLectureIdSessionRouteImport } from './routes/api/learn/ai-tutor/$lectureId/session'
import { Route as ApiLearnAiTutorLectureIdFeedbackRouteImport } from './routes/api/learn/ai-tutor/$lectureId/feedback'
import { Route as ApiLearnAiTutorLectureIdDispatchRouteImport } from './routes/api/learn/ai-tutor/$lectureId/dispatch'
import { Route as ApiLearnAiChatLectureIdSendRouteImport } from './routes/api/learn/ai-chat/$lectureId/send'
import { Route as ApiLearnAiChatLectureIdHistoryRouteImport } from './routes/api/learn/ai-chat/$lectureId/history'

const protectedLayoutRouteRoute = protectedLayoutRouteRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedZoomIndexRoute = protectedZoomIndexRouteImport.update({
  id: '/(protected)/zoom/',
  path: '/zoom/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutIndexRoute = protectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRouteRoute,
} as any)
const authSwitchAccountIndexRoute = authSwitchAccountIndexRouteImport.update({
  id: '/(auth)/switch-account/',
  path: '/switch-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninIndexRoute = authSigninIndexRouteImport.update({
  id: '/(auth)/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearnBatchesRoute = ApiLearnBatchesRouteImport.update({
  id: '/api/learn/batches',
  path: '/api/learn/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearnBatchDataRoute = ApiLearnBatchDataRouteImport.update({
  id: '/api/learn/batch-data',
  path: '/api/learn/batch-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardScheduleRoute = ApiDashboardScheduleRouteImport.update({
  id: '/api/dashboard/schedule',
  path: '/api/dashboard/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardProductUpdatesRoute =
  ApiDashboardProductUpdatesRouteImport.update({
    id: '/api/dashboard/product-updates',
    path: '/api/dashboard/product-updates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDashboardPendingTasksRoute =
  ApiDashboardPendingTasksRouteImport.update({
    id: '/api/dashboard/pending-tasks',
    path: '/api/dashboard/pending-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDashboardBannersRoute = ApiDashboardBannersRouteImport.update({
  id: '/api/dashboard/banners',
  path: '/api/dashboard/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardAnnouncementsRoute =
  ApiDashboardAnnouncementsRouteImport.update({
    id: '/api/dashboard/announcements',
    path: '/api/dashboard/announcements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDashboardActionBannersRoute =
  ApiDashboardActionBannersRouteImport.update({
    id: '/api/dashboard/action-banners',
    path: '/api/dashboard/action-banners',
    getParentRoute: () => rootRouteImport,
  } as any)
const authV2ResetPasswordRoute = authV2ResetPasswordRouteImport.update({
  id: '/(auth)/v2/reset-password',
  path: '/v2/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authV2MeRoute = authV2MeRouteImport.update({
  id: '/(auth)/v2/me',
  path: '/v2/me',
  getParentRoute: () => rootRouteImport,
} as any)
const authV2ForgotPasswordRoute = authV2ForgotPasswordRouteImport.update({
  id: '/(auth)/v2/forgot-password',
  path: '/v2/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutMasaiverseRouteRoute =
  protectedLayoutMasaiverseRouteRouteImport.update({
    id: '/masaiverse',
    path: '/masaiverse',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutMasaiverseIndexRoute =
  protectedLayoutMasaiverseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedLayoutMasaiverseRouteRoute,
  } as any)
const protectedLayoutLearnIndexRoute =
  protectedLayoutLearnIndexRouteImport.update({
    id: '/learn/',
    path: '/learn/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const authV2LoginIndexRoute = authV2LoginIndexRouteImport.update({
  id: '/(auth)/v2/login/',
  path: '/v2/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordTokenIndexRoute =
  authResetPasswordTokenIndexRouteImport.update({
    id: '/(auth)/reset-password/$token/',
    path: '/reset-password/$token/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnSubmissionsSubmissionIdRoute =
  ApiLearnSubmissionsSubmissionIdRouteImport.update({
    id: '/api/learn/submissions/$submissionId',
    path: '/api/learn/submissions/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnResourcesResourceIdRoute =
  ApiLearnResourcesResourceIdRouteImport.update({
    id: '/api/learn/resources/$resourceId',
    path: '/api/learn/resources/$resourceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnLecturesLectureIdRoute =
  ApiLearnLecturesLectureIdRouteImport.update({
    id: '/api/learn/lectures/$lectureId',
    path: '/api/learn/lectures/$lectureId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnAssignmentsAssignmentIdRoute =
  ApiLearnAssignmentsAssignmentIdRouteImport.update({
    id: '/api/learn/assignments/$assignmentId',
    path: '/api/learn/assignments/$assignmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnAiTutorLimitRoute = ApiLearnAiTutorLimitRouteImport.update({
  id: '/api/learn/ai-tutor/limit',
  path: '/api/learn/ai-tutor/limit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearnAiTutorEndRoute = ApiLearnAiTutorEndRouteImport.update({
  id: '/api/learn/ai-tutor/end',
  path: '/api/learn/ai-tutor/end',
  getParentRoute: () => rootRouteImport,
} as any)
const authV2LoginVerifyOtpRoute = authV2LoginVerifyOtpRouteImport.update({
  id: '/(auth)/v2/login/verify-otp',
  path: '/v2/login/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authV2LoginRequestOtpRoute = authV2LoginRequestOtpRouteImport.update({
  id: '/(auth)/v2/login/request-otp',
  path: '/v2/login/request-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authV2AuthUseAccountRoute = authV2AuthUseAccountRouteImport.update({
  id: '/(auth)/v2/auth/use-account',
  path: '/v2/auth/use-account',
  getParentRoute: () => rootRouteImport,
} as any)
const authV2AuthLinkedAccountsRoute =
  authV2AuthLinkedAccountsRouteImport.update({
    id: '/(auth)/v2/auth/linked-accounts',
    path: '/v2/auth/linked-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const protectedLayoutResourcesResourceIdRouteRoute =
  protectedLayoutResourcesResourceIdRouteRouteImport.update({
    id: '/resources_/$resourceId',
    path: '/resources/$resourceId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutLecturesLectureIdRouteRoute =
  protectedLayoutLecturesLectureIdRouteRouteImport.update({
    id: '/lectures_/$lectureId',
    path: '/lectures/$lectureId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutAssignmentsAssignmentIdRouteRoute =
  protectedLayoutAssignmentsAssignmentIdRouteRouteImport.update({
    id: '/assignments_/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute =
  ApiLearnSubmissionsSubmissionIdViewOnPlatformRouteImport.update({
    id: '/view-on-platform',
    path: '/view-on-platform',
    getParentRoute: () => ApiLearnSubmissionsSubmissionIdRoute,
  } as any)
const ApiLearnAssignmentsAssignmentIdSubmissionsRoute =
  ApiLearnAssignmentsAssignmentIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => ApiLearnAssignmentsAssignmentIdRoute,
  } as any)
const ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute =
  ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRouteImport.update({
    id: '/assess-platform-url',
    path: '/assess-platform-url',
    getParentRoute: () => ApiLearnAssignmentsAssignmentIdRoute,
  } as any)
const ApiLearnAiTutorLectureIdTranscriptRoute =
  ApiLearnAiTutorLectureIdTranscriptRouteImport.update({
    id: '/api/learn/ai-tutor/$lectureId/transcript',
    path: '/api/learn/ai-tutor/$lectureId/transcript',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnAiTutorLectureIdSessionRoute =
  ApiLearnAiTutorLectureIdSessionRouteImport.update({
    id: '/api/learn/ai-tutor/$lectureId/session',
    path: '/api/learn/ai-tutor/$lectureId/session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnAiTutorLectureIdFeedbackRoute =
  ApiLearnAiTutorLectureIdFeedbackRouteImport.update({
    id: '/api/learn/ai-tutor/$lectureId/feedback',
    path: '/api/learn/ai-tutor/$lectureId/feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnAiTutorLectureIdDispatchRoute =
  ApiLearnAiTutorLectureIdDispatchRouteImport.update({
    id: '/api/learn/ai-tutor/$lectureId/dispatch',
    path: '/api/learn/ai-tutor/$lectureId/dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnAiChatLectureIdSendRoute =
  ApiLearnAiChatLectureIdSendRouteImport.update({
    id: '/api/learn/ai-chat/$lectureId/send',
    path: '/api/learn/ai-chat/$lectureId/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnAiChatLectureIdHistoryRoute =
  ApiLearnAiChatLectureIdHistoryRouteImport.update({
    id: '/api/learn/ai-chat/$lectureId/history',
    path: '/api/learn/ai-chat/$lectureId/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/masaiverse': typeof protectedLayoutMasaiverseRouteRouteWithChildren
  '/v2/forgot-password': typeof authV2ForgotPasswordRoute
  '/v2/me': typeof authV2MeRoute
  '/v2/reset-password': typeof authV2ResetPasswordRoute
  '/api/dashboard/action-banners': typeof ApiDashboardActionBannersRoute
  '/api/dashboard/announcements': typeof ApiDashboardAnnouncementsRoute
  '/api/dashboard/banners': typeof ApiDashboardBannersRoute
  '/api/dashboard/pending-tasks': typeof ApiDashboardPendingTasksRoute
  '/api/dashboard/product-updates': typeof ApiDashboardProductUpdatesRoute
  '/api/dashboard/schedule': typeof ApiDashboardScheduleRoute
  '/api/learn/batch-data': typeof ApiLearnBatchDataRoute
  '/api/learn/batches': typeof ApiLearnBatchesRoute
  '/login/': typeof authLoginIndexRoute
  '/signin/': typeof authSigninIndexRoute
  '/switch-account/': typeof authSwitchAccountIndexRoute
  '/': typeof protectedLayoutIndexRoute
  '/zoom/': typeof protectedZoomIndexRoute
  '/assignments/$assignmentId': typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  '/lectures/$lectureId': typeof protectedLayoutLecturesLectureIdRouteRoute
  '/resources/$resourceId': typeof protectedLayoutResourcesResourceIdRouteRoute
  '/v2/auth/linked-accounts': typeof authV2AuthLinkedAccountsRoute
  '/v2/auth/use-account': typeof authV2AuthUseAccountRoute
  '/v2/login/request-otp': typeof authV2LoginRequestOtpRoute
  '/v2/login/verify-otp': typeof authV2LoginVerifyOtpRoute
  '/api/learn/ai-tutor/end': typeof ApiLearnAiTutorEndRoute
  '/api/learn/ai-tutor/limit': typeof ApiLearnAiTutorLimitRoute
  '/api/learn/assignments/$assignmentId': typeof ApiLearnAssignmentsAssignmentIdRouteWithChildren
  '/api/learn/lectures/$lectureId': typeof ApiLearnLecturesLectureIdRoute
  '/api/learn/resources/$resourceId': typeof ApiLearnResourcesResourceIdRoute
  '/api/learn/submissions/$submissionId': typeof ApiLearnSubmissionsSubmissionIdRouteWithChildren
  '/reset-password/$token/': typeof authResetPasswordTokenIndexRoute
  '/v2/login/': typeof authV2LoginIndexRoute
  '/learn/': typeof protectedLayoutLearnIndexRoute
  '/masaiverse/': typeof protectedLayoutMasaiverseIndexRoute
  '/api/learn/ai-chat/$lectureId/history': typeof ApiLearnAiChatLectureIdHistoryRoute
  '/api/learn/ai-chat/$lectureId/send': typeof ApiLearnAiChatLectureIdSendRoute
  '/api/learn/ai-tutor/$lectureId/dispatch': typeof ApiLearnAiTutorLectureIdDispatchRoute
  '/api/learn/ai-tutor/$lectureId/feedback': typeof ApiLearnAiTutorLectureIdFeedbackRoute
  '/api/learn/ai-tutor/$lectureId/session': typeof ApiLearnAiTutorLectureIdSessionRoute
  '/api/learn/ai-tutor/$lectureId/transcript': typeof ApiLearnAiTutorLectureIdTranscriptRoute
  '/api/learn/assignments/$assignmentId/assess-platform-url': typeof ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute
  '/api/learn/assignments/$assignmentId/submissions': typeof ApiLearnAssignmentsAssignmentIdSubmissionsRoute
  '/api/learn/submissions/$submissionId/view-on-platform': typeof ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute
}
export interface FileRoutesByTo {
  '/v2/forgot-password': typeof authV2ForgotPasswordRoute
  '/v2/me': typeof authV2MeRoute
  '/v2/reset-password': typeof authV2ResetPasswordRoute
  '/api/dashboard/action-banners': typeof ApiDashboardActionBannersRoute
  '/api/dashboard/announcements': typeof ApiDashboardAnnouncementsRoute
  '/api/dashboard/banners': typeof ApiDashboardBannersRoute
  '/api/dashboard/pending-tasks': typeof ApiDashboardPendingTasksRoute
  '/api/dashboard/product-updates': typeof ApiDashboardProductUpdatesRoute
  '/api/dashboard/schedule': typeof ApiDashboardScheduleRoute
  '/api/learn/batch-data': typeof ApiLearnBatchDataRoute
  '/api/learn/batches': typeof ApiLearnBatchesRoute
  '/login': typeof authLoginIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/switch-account': typeof authSwitchAccountIndexRoute
  '/': typeof protectedLayoutIndexRoute
  '/zoom': typeof protectedZoomIndexRoute
  '/assignments/$assignmentId': typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  '/lectures/$lectureId': typeof protectedLayoutLecturesLectureIdRouteRoute
  '/resources/$resourceId': typeof protectedLayoutResourcesResourceIdRouteRoute
  '/v2/auth/linked-accounts': typeof authV2AuthLinkedAccountsRoute
  '/v2/auth/use-account': typeof authV2AuthUseAccountRoute
  '/v2/login/request-otp': typeof authV2LoginRequestOtpRoute
  '/v2/login/verify-otp': typeof authV2LoginVerifyOtpRoute
  '/api/learn/ai-tutor/end': typeof ApiLearnAiTutorEndRoute
  '/api/learn/ai-tutor/limit': typeof ApiLearnAiTutorLimitRoute
  '/api/learn/assignments/$assignmentId': typeof ApiLearnAssignmentsAssignmentIdRouteWithChildren
  '/api/learn/lectures/$lectureId': typeof ApiLearnLecturesLectureIdRoute
  '/api/learn/resources/$resourceId': typeof ApiLearnResourcesResourceIdRoute
  '/api/learn/submissions/$submissionId': typeof ApiLearnSubmissionsSubmissionIdRouteWithChildren
  '/reset-password/$token': typeof authResetPasswordTokenIndexRoute
  '/v2/login': typeof authV2LoginIndexRoute
  '/learn': typeof protectedLayoutLearnIndexRoute
  '/masaiverse': typeof protectedLayoutMasaiverseIndexRoute
  '/api/learn/ai-chat/$lectureId/history': typeof ApiLearnAiChatLectureIdHistoryRoute
  '/api/learn/ai-chat/$lectureId/send': typeof ApiLearnAiChatLectureIdSendRoute
  '/api/learn/ai-tutor/$lectureId/dispatch': typeof ApiLearnAiTutorLectureIdDispatchRoute
  '/api/learn/ai-tutor/$lectureId/feedback': typeof ApiLearnAiTutorLectureIdFeedbackRoute
  '/api/learn/ai-tutor/$lectureId/session': typeof ApiLearnAiTutorLectureIdSessionRoute
  '/api/learn/ai-tutor/$lectureId/transcript': typeof ApiLearnAiTutorLectureIdTranscriptRoute
  '/api/learn/assignments/$assignmentId/assess-platform-url': typeof ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute
  '/api/learn/assignments/$assignmentId/submissions': typeof ApiLearnAssignmentsAssignmentIdSubmissionsRoute
  '/api/learn/submissions/$submissionId/view-on-platform': typeof ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)/_layout': typeof protectedLayoutRouteRouteWithChildren
  '/(protected)/_layout/masaiverse': typeof protectedLayoutMasaiverseRouteRouteWithChildren
  '/(auth)/v2/forgot-password': typeof authV2ForgotPasswordRoute
  '/(auth)/v2/me': typeof authV2MeRoute
  '/(auth)/v2/reset-password': typeof authV2ResetPasswordRoute
  '/api/dashboard/action-banners': typeof ApiDashboardActionBannersRoute
  '/api/dashboard/announcements': typeof ApiDashboardAnnouncementsRoute
  '/api/dashboard/banners': typeof ApiDashboardBannersRoute
  '/api/dashboard/pending-tasks': typeof ApiDashboardPendingTasksRoute
  '/api/dashboard/product-updates': typeof ApiDashboardProductUpdatesRoute
  '/api/dashboard/schedule': typeof ApiDashboardScheduleRoute
  '/api/learn/batch-data': typeof ApiLearnBatchDataRoute
  '/api/learn/batches': typeof ApiLearnBatchesRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/signin/': typeof authSigninIndexRoute
  '/(auth)/switch-account/': typeof authSwitchAccountIndexRoute
  '/(protected)/_layout/': typeof protectedLayoutIndexRoute
  '/(protected)/zoom/': typeof protectedZoomIndexRoute
  '/(protected)/_layout/assignments_/$assignmentId': typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  '/(protected)/_layout/lectures_/$lectureId': typeof protectedLayoutLecturesLectureIdRouteRoute
  '/(protected)/_layout/resources_/$resourceId': typeof protectedLayoutResourcesResourceIdRouteRoute
  '/(auth)/v2/auth/linked-accounts': typeof authV2AuthLinkedAccountsRoute
  '/(auth)/v2/auth/use-account': typeof authV2AuthUseAccountRoute
  '/(auth)/v2/login/request-otp': typeof authV2LoginRequestOtpRoute
  '/(auth)/v2/login/verify-otp': typeof authV2LoginVerifyOtpRoute
  '/api/learn/ai-tutor/end': typeof ApiLearnAiTutorEndRoute
  '/api/learn/ai-tutor/limit': typeof ApiLearnAiTutorLimitRoute
  '/api/learn/assignments/$assignmentId': typeof ApiLearnAssignmentsAssignmentIdRouteWithChildren
  '/api/learn/lectures/$lectureId': typeof ApiLearnLecturesLectureIdRoute
  '/api/learn/resources/$resourceId': typeof ApiLearnResourcesResourceIdRoute
  '/api/learn/submissions/$submissionId': typeof ApiLearnSubmissionsSubmissionIdRouteWithChildren
  '/(auth)/reset-password/$token/': typeof authResetPasswordTokenIndexRoute
  '/(auth)/v2/login/': typeof authV2LoginIndexRoute
  '/(protected)/_layout/learn/': typeof protectedLayoutLearnIndexRoute
  '/(protected)/_layout/masaiverse/': typeof protectedLayoutMasaiverseIndexRoute
  '/api/learn/ai-chat/$lectureId/history': typeof ApiLearnAiChatLectureIdHistoryRoute
  '/api/learn/ai-chat/$lectureId/send': typeof ApiLearnAiChatLectureIdSendRoute
  '/api/learn/ai-tutor/$lectureId/dispatch': typeof ApiLearnAiTutorLectureIdDispatchRoute
  '/api/learn/ai-tutor/$lectureId/feedback': typeof ApiLearnAiTutorLectureIdFeedbackRoute
  '/api/learn/ai-tutor/$lectureId/session': typeof ApiLearnAiTutorLectureIdSessionRoute
  '/api/learn/ai-tutor/$lectureId/transcript': typeof ApiLearnAiTutorLectureIdTranscriptRoute
  '/api/learn/assignments/$assignmentId/assess-platform-url': typeof ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute
  '/api/learn/assignments/$assignmentId/submissions': typeof ApiLearnAssignmentsAssignmentIdSubmissionsRoute
  '/api/learn/submissions/$submissionId/view-on-platform': typeof ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/masaiverse'
    | '/v2/forgot-password'
    | '/v2/me'
    | '/v2/reset-password'
    | '/api/dashboard/action-banners'
    | '/api/dashboard/announcements'
    | '/api/dashboard/banners'
    | '/api/dashboard/pending-tasks'
    | '/api/dashboard/product-updates'
    | '/api/dashboard/schedule'
    | '/api/learn/batch-data'
    | '/api/learn/batches'
    | '/login/'
    | '/signin/'
    | '/switch-account/'
    | '/'
    | '/zoom/'
    | '/assignments/$assignmentId'
    | '/lectures/$lectureId'
    | '/resources/$resourceId'
    | '/v2/auth/linked-accounts'
    | '/v2/auth/use-account'
    | '/v2/login/request-otp'
    | '/v2/login/verify-otp'
    | '/api/learn/ai-tutor/end'
    | '/api/learn/ai-tutor/limit'
    | '/api/learn/assignments/$assignmentId'
    | '/api/learn/lectures/$lectureId'
    | '/api/learn/resources/$resourceId'
    | '/api/learn/submissions/$submissionId'
    | '/reset-password/$token/'
    | '/v2/login/'
    | '/learn/'
    | '/masaiverse/'
    | '/api/learn/ai-chat/$lectureId/history'
    | '/api/learn/ai-chat/$lectureId/send'
    | '/api/learn/ai-tutor/$lectureId/dispatch'
    | '/api/learn/ai-tutor/$lectureId/feedback'
    | '/api/learn/ai-tutor/$lectureId/session'
    | '/api/learn/ai-tutor/$lectureId/transcript'
    | '/api/learn/assignments/$assignmentId/assess-platform-url'
    | '/api/learn/assignments/$assignmentId/submissions'
    | '/api/learn/submissions/$submissionId/view-on-platform'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/v2/forgot-password'
    | '/v2/me'
    | '/v2/reset-password'
    | '/api/dashboard/action-banners'
    | '/api/dashboard/announcements'
    | '/api/dashboard/banners'
    | '/api/dashboard/pending-tasks'
    | '/api/dashboard/product-updates'
    | '/api/dashboard/schedule'
    | '/api/learn/batch-data'
    | '/api/learn/batches'
    | '/login'
    | '/signin'
    | '/switch-account'
    | '/'
    | '/zoom'
    | '/assignments/$assignmentId'
    | '/lectures/$lectureId'
    | '/resources/$resourceId'
    | '/v2/auth/linked-accounts'
    | '/v2/auth/use-account'
    | '/v2/login/request-otp'
    | '/v2/login/verify-otp'
    | '/api/learn/ai-tutor/end'
    | '/api/learn/ai-tutor/limit'
    | '/api/learn/assignments/$assignmentId'
    | '/api/learn/lectures/$lectureId'
    | '/api/learn/resources/$resourceId'
    | '/api/learn/submissions/$submissionId'
    | '/reset-password/$token'
    | '/v2/login'
    | '/learn'
    | '/masaiverse'
    | '/api/learn/ai-chat/$lectureId/history'
    | '/api/learn/ai-chat/$lectureId/send'
    | '/api/learn/ai-tutor/$lectureId/dispatch'
    | '/api/learn/ai-tutor/$lectureId/feedback'
    | '/api/learn/ai-tutor/$lectureId/session'
    | '/api/learn/ai-tutor/$lectureId/transcript'
    | '/api/learn/assignments/$assignmentId/assess-platform-url'
    | '/api/learn/assignments/$assignmentId/submissions'
    | '/api/learn/submissions/$submissionId/view-on-platform'
  id:
    | '__root__'
    | '/(protected)/_layout'
    | '/(protected)/_layout/masaiverse'
    | '/(auth)/v2/forgot-password'
    | '/(auth)/v2/me'
    | '/(auth)/v2/reset-password'
    | '/api/dashboard/action-banners'
    | '/api/dashboard/announcements'
    | '/api/dashboard/banners'
    | '/api/dashboard/pending-tasks'
    | '/api/dashboard/product-updates'
    | '/api/dashboard/schedule'
    | '/api/learn/batch-data'
    | '/api/learn/batches'
    | '/(auth)/login/'
    | '/(auth)/signin/'
    | '/(auth)/switch-account/'
    | '/(protected)/_layout/'
    | '/(protected)/zoom/'
    | '/(protected)/_layout/assignments_/$assignmentId'
    | '/(protected)/_layout/lectures_/$lectureId'
    | '/(protected)/_layout/resources_/$resourceId'
    | '/(auth)/v2/auth/linked-accounts'
    | '/(auth)/v2/auth/use-account'
    | '/(auth)/v2/login/request-otp'
    | '/(auth)/v2/login/verify-otp'
    | '/api/learn/ai-tutor/end'
    | '/api/learn/ai-tutor/limit'
    | '/api/learn/assignments/$assignmentId'
    | '/api/learn/lectures/$lectureId'
    | '/api/learn/resources/$resourceId'
    | '/api/learn/submissions/$submissionId'
    | '/(auth)/reset-password/$token/'
    | '/(auth)/v2/login/'
    | '/(protected)/_layout/learn/'
    | '/(protected)/_layout/masaiverse/'
    | '/api/learn/ai-chat/$lectureId/history'
    | '/api/learn/ai-chat/$lectureId/send'
    | '/api/learn/ai-tutor/$lectureId/dispatch'
    | '/api/learn/ai-tutor/$lectureId/feedback'
    | '/api/learn/ai-tutor/$lectureId/session'
    | '/api/learn/ai-tutor/$lectureId/transcript'
    | '/api/learn/assignments/$assignmentId/assess-platform-url'
    | '/api/learn/assignments/$assignmentId/submissions'
    | '/api/learn/submissions/$submissionId/view-on-platform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedLayoutRouteRoute: typeof protectedLayoutRouteRouteWithChildren
  authV2ForgotPasswordRoute: typeof authV2ForgotPasswordRoute
  authV2MeRoute: typeof authV2MeRoute
  authV2ResetPasswordRoute: typeof authV2ResetPasswordRoute
  ApiDashboardActionBannersRoute: typeof ApiDashboardActionBannersRoute
  ApiDashboardAnnouncementsRoute: typeof ApiDashboardAnnouncementsRoute
  ApiDashboardBannersRoute: typeof ApiDashboardBannersRoute
  ApiDashboardPendingTasksRoute: typeof ApiDashboardPendingTasksRoute
  ApiDashboardProductUpdatesRoute: typeof ApiDashboardProductUpdatesRoute
  ApiDashboardScheduleRoute: typeof ApiDashboardScheduleRoute
  ApiLearnBatchDataRoute: typeof ApiLearnBatchDataRoute
  ApiLearnBatchesRoute: typeof ApiLearnBatchesRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authSigninIndexRoute: typeof authSigninIndexRoute
  authSwitchAccountIndexRoute: typeof authSwitchAccountIndexRoute
  protectedZoomIndexRoute: typeof protectedZoomIndexRoute
  authV2AuthLinkedAccountsRoute: typeof authV2AuthLinkedAccountsRoute
  authV2AuthUseAccountRoute: typeof authV2AuthUseAccountRoute
  authV2LoginRequestOtpRoute: typeof authV2LoginRequestOtpRoute
  authV2LoginVerifyOtpRoute: typeof authV2LoginVerifyOtpRoute
  ApiLearnAiTutorEndRoute: typeof ApiLearnAiTutorEndRoute
  ApiLearnAiTutorLimitRoute: typeof ApiLearnAiTutorLimitRoute
  ApiLearnAssignmentsAssignmentIdRoute: typeof ApiLearnAssignmentsAssignmentIdRouteWithChildren
  ApiLearnLecturesLectureIdRoute: typeof ApiLearnLecturesLectureIdRoute
  ApiLearnResourcesResourceIdRoute: typeof ApiLearnResourcesResourceIdRoute
  ApiLearnSubmissionsSubmissionIdRoute: typeof ApiLearnSubmissionsSubmissionIdRouteWithChildren
  authResetPasswordTokenIndexRoute: typeof authResetPasswordTokenIndexRoute
  authV2LoginIndexRoute: typeof authV2LoginIndexRoute
  ApiLearnAiChatLectureIdHistoryRoute: typeof ApiLearnAiChatLectureIdHistoryRoute
  ApiLearnAiChatLectureIdSendRoute: typeof ApiLearnAiChatLectureIdSendRoute
  ApiLearnAiTutorLectureIdDispatchRoute: typeof ApiLearnAiTutorLectureIdDispatchRoute
  ApiLearnAiTutorLectureIdFeedbackRoute: typeof ApiLearnAiTutorLectureIdFeedbackRoute
  ApiLearnAiTutorLectureIdSessionRoute: typeof ApiLearnAiTutorLectureIdSessionRoute
  ApiLearnAiTutorLectureIdTranscriptRoute: typeof ApiLearnAiTutorLectureIdTranscriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/zoom/': {
      id: '/(protected)/zoom/'
      path: '/zoom'
      fullPath: '/zoom/'
      preLoaderRoute: typeof protectedZoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/': {
      id: '/(protected)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(auth)/switch-account/': {
      id: '/(auth)/switch-account/'
      path: '/switch-account'
      fullPath: '/switch-account/'
      preLoaderRoute: typeof authSwitchAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin/': {
      id: '/(auth)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof authSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/batches': {
      id: '/api/learn/batches'
      path: '/api/learn/batches'
      fullPath: '/api/learn/batches'
      preLoaderRoute: typeof ApiLearnBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/batch-data': {
      id: '/api/learn/batch-data'
      path: '/api/learn/batch-data'
      fullPath: '/api/learn/batch-data'
      preLoaderRoute: typeof ApiLearnBatchDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/schedule': {
      id: '/api/dashboard/schedule'
      path: '/api/dashboard/schedule'
      fullPath: '/api/dashboard/schedule'
      preLoaderRoute: typeof ApiDashboardScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/product-updates': {
      id: '/api/dashboard/product-updates'
      path: '/api/dashboard/product-updates'
      fullPath: '/api/dashboard/product-updates'
      preLoaderRoute: typeof ApiDashboardProductUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/pending-tasks': {
      id: '/api/dashboard/pending-tasks'
      path: '/api/dashboard/pending-tasks'
      fullPath: '/api/dashboard/pending-tasks'
      preLoaderRoute: typeof ApiDashboardPendingTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/banners': {
      id: '/api/dashboard/banners'
      path: '/api/dashboard/banners'
      fullPath: '/api/dashboard/banners'
      preLoaderRoute: typeof ApiDashboardBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/announcements': {
      id: '/api/dashboard/announcements'
      path: '/api/dashboard/announcements'
      fullPath: '/api/dashboard/announcements'
      preLoaderRoute: typeof ApiDashboardAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/action-banners': {
      id: '/api/dashboard/action-banners'
      path: '/api/dashboard/action-banners'
      fullPath: '/api/dashboard/action-banners'
      preLoaderRoute: typeof ApiDashboardActionBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/v2/reset-password': {
      id: '/(auth)/v2/reset-password'
      path: '/v2/reset-password'
      fullPath: '/v2/reset-password'
      preLoaderRoute: typeof authV2ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/v2/me': {
      id: '/(auth)/v2/me'
      path: '/v2/me'
      fullPath: '/v2/me'
      preLoaderRoute: typeof authV2MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/v2/forgot-password': {
      id: '/(auth)/v2/forgot-password'
      path: '/v2/forgot-password'
      fullPath: '/v2/forgot-password'
      preLoaderRoute: typeof authV2ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/masaiverse': {
      id: '/(protected)/_layout/masaiverse'
      path: '/masaiverse'
      fullPath: '/masaiverse'
      preLoaderRoute: typeof protectedLayoutMasaiverseRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/masaiverse/': {
      id: '/(protected)/_layout/masaiverse/'
      path: '/'
      fullPath: '/masaiverse/'
      preLoaderRoute: typeof protectedLayoutMasaiverseIndexRouteImport
      parentRoute: typeof protectedLayoutMasaiverseRouteRoute
    }
    '/(protected)/_layout/learn/': {
      id: '/(protected)/_layout/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof protectedLayoutLearnIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(auth)/v2/login/': {
      id: '/(auth)/v2/login/'
      path: '/v2/login'
      fullPath: '/v2/login/'
      preLoaderRoute: typeof authV2LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password/$token/': {
      id: '/(auth)/reset-password/$token/'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token/'
      preLoaderRoute: typeof authResetPasswordTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/submissions/$submissionId': {
      id: '/api/learn/submissions/$submissionId'
      path: '/api/learn/submissions/$submissionId'
      fullPath: '/api/learn/submissions/$submissionId'
      preLoaderRoute: typeof ApiLearnSubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/resources/$resourceId': {
      id: '/api/learn/resources/$resourceId'
      path: '/api/learn/resources/$resourceId'
      fullPath: '/api/learn/resources/$resourceId'
      preLoaderRoute: typeof ApiLearnResourcesResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/lectures/$lectureId': {
      id: '/api/learn/lectures/$lectureId'
      path: '/api/learn/lectures/$lectureId'
      fullPath: '/api/learn/lectures/$lectureId'
      preLoaderRoute: typeof ApiLearnLecturesLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/assignments/$assignmentId': {
      id: '/api/learn/assignments/$assignmentId'
      path: '/api/learn/assignments/$assignmentId'
      fullPath: '/api/learn/assignments/$assignmentId'
      preLoaderRoute: typeof ApiLearnAssignmentsAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/ai-tutor/limit': {
      id: '/api/learn/ai-tutor/limit'
      path: '/api/learn/ai-tutor/limit'
      fullPath: '/api/learn/ai-tutor/limit'
      preLoaderRoute: typeof ApiLearnAiTutorLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/ai-tutor/end': {
      id: '/api/learn/ai-tutor/end'
      path: '/api/learn/ai-tutor/end'
      fullPath: '/api/learn/ai-tutor/end'
      preLoaderRoute: typeof ApiLearnAiTutorEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/v2/login/verify-otp': {
      id: '/(auth)/v2/login/verify-otp'
      path: '/v2/login/verify-otp'
      fullPath: '/v2/login/verify-otp'
      preLoaderRoute: typeof authV2LoginVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/v2/login/request-otp': {
      id: '/(auth)/v2/login/request-otp'
      path: '/v2/login/request-otp'
      fullPath: '/v2/login/request-otp'
      preLoaderRoute: typeof authV2LoginRequestOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/v2/auth/use-account': {
      id: '/(auth)/v2/auth/use-account'
      path: '/v2/auth/use-account'
      fullPath: '/v2/auth/use-account'
      preLoaderRoute: typeof authV2AuthUseAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/v2/auth/linked-accounts': {
      id: '/(auth)/v2/auth/linked-accounts'
      path: '/v2/auth/linked-accounts'
      fullPath: '/v2/auth/linked-accounts'
      preLoaderRoute: typeof authV2AuthLinkedAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/resources_/$resourceId': {
      id: '/(protected)/_layout/resources_/$resourceId'
      path: '/resources/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof protectedLayoutResourcesResourceIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/lectures_/$lectureId': {
      id: '/(protected)/_layout/lectures_/$lectureId'
      path: '/lectures/$lectureId'
      fullPath: '/lectures/$lectureId'
      preLoaderRoute: typeof protectedLayoutLecturesLectureIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/assignments_/$assignmentId': {
      id: '/(protected)/_layout/assignments_/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof protectedLayoutAssignmentsAssignmentIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/api/learn/submissions/$submissionId/view-on-platform': {
      id: '/api/learn/submissions/$submissionId/view-on-platform'
      path: '/view-on-platform'
      fullPath: '/api/learn/submissions/$submissionId/view-on-platform'
      preLoaderRoute: typeof ApiLearnSubmissionsSubmissionIdViewOnPlatformRouteImport
      parentRoute: typeof ApiLearnSubmissionsSubmissionIdRoute
    }
    '/api/learn/assignments/$assignmentId/submissions': {
      id: '/api/learn/assignments/$assignmentId/submissions'
      path: '/submissions'
      fullPath: '/api/learn/assignments/$assignmentId/submissions'
      preLoaderRoute: typeof ApiLearnAssignmentsAssignmentIdSubmissionsRouteImport
      parentRoute: typeof ApiLearnAssignmentsAssignmentIdRoute
    }
    '/api/learn/assignments/$assignmentId/assess-platform-url': {
      id: '/api/learn/assignments/$assignmentId/assess-platform-url'
      path: '/assess-platform-url'
      fullPath: '/api/learn/assignments/$assignmentId/assess-platform-url'
      preLoaderRoute: typeof ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRouteImport
      parentRoute: typeof ApiLearnAssignmentsAssignmentIdRoute
    }
    '/api/learn/ai-tutor/$lectureId/transcript': {
      id: '/api/learn/ai-tutor/$lectureId/transcript'
      path: '/api/learn/ai-tutor/$lectureId/transcript'
      fullPath: '/api/learn/ai-tutor/$lectureId/transcript'
      preLoaderRoute: typeof ApiLearnAiTutorLectureIdTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/ai-tutor/$lectureId/session': {
      id: '/api/learn/ai-tutor/$lectureId/session'
      path: '/api/learn/ai-tutor/$lectureId/session'
      fullPath: '/api/learn/ai-tutor/$lectureId/session'
      preLoaderRoute: typeof ApiLearnAiTutorLectureIdSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/ai-tutor/$lectureId/feedback': {
      id: '/api/learn/ai-tutor/$lectureId/feedback'
      path: '/api/learn/ai-tutor/$lectureId/feedback'
      fullPath: '/api/learn/ai-tutor/$lectureId/feedback'
      preLoaderRoute: typeof ApiLearnAiTutorLectureIdFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/ai-tutor/$lectureId/dispatch': {
      id: '/api/learn/ai-tutor/$lectureId/dispatch'
      path: '/api/learn/ai-tutor/$lectureId/dispatch'
      fullPath: '/api/learn/ai-tutor/$lectureId/dispatch'
      preLoaderRoute: typeof ApiLearnAiTutorLectureIdDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/ai-chat/$lectureId/send': {
      id: '/api/learn/ai-chat/$lectureId/send'
      path: '/api/learn/ai-chat/$lectureId/send'
      fullPath: '/api/learn/ai-chat/$lectureId/send'
      preLoaderRoute: typeof ApiLearnAiChatLectureIdSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/ai-chat/$lectureId/history': {
      id: '/api/learn/ai-chat/$lectureId/history'
      path: '/api/learn/ai-chat/$lectureId/history'
      fullPath: '/api/learn/ai-chat/$lectureId/history'
      preLoaderRoute: typeof ApiLearnAiChatLectureIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface protectedLayoutMasaiverseRouteRouteChildren {
  protectedLayoutMasaiverseIndexRoute: typeof protectedLayoutMasaiverseIndexRoute
}

const protectedLayoutMasaiverseRouteRouteChildren: protectedLayoutMasaiverseRouteRouteChildren =
  {
    protectedLayoutMasaiverseIndexRoute: protectedLayoutMasaiverseIndexRoute,
  }

const protectedLayoutMasaiverseRouteRouteWithChildren =
  protectedLayoutMasaiverseRouteRoute._addFileChildren(
    protectedLayoutMasaiverseRouteRouteChildren,
  )

interface protectedLayoutRouteRouteChildren {
  protectedLayoutMasaiverseRouteRoute: typeof protectedLayoutMasaiverseRouteRouteWithChildren
  protectedLayoutIndexRoute: typeof protectedLayoutIndexRoute
  protectedLayoutAssignmentsAssignmentIdRouteRoute: typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  protectedLayoutLecturesLectureIdRouteRoute: typeof protectedLayoutLecturesLectureIdRouteRoute
  protectedLayoutResourcesResourceIdRouteRoute: typeof protectedLayoutResourcesResourceIdRouteRoute
  protectedLayoutLearnIndexRoute: typeof protectedLayoutLearnIndexRoute
}

const protectedLayoutRouteRouteChildren: protectedLayoutRouteRouteChildren = {
  protectedLayoutMasaiverseRouteRoute:
    protectedLayoutMasaiverseRouteRouteWithChildren,
  protectedLayoutIndexRoute: protectedLayoutIndexRoute,
  protectedLayoutAssignmentsAssignmentIdRouteRoute:
    protectedLayoutAssignmentsAssignmentIdRouteRoute,
  protectedLayoutLecturesLectureIdRouteRoute:
    protectedLayoutLecturesLectureIdRouteRoute,
  protectedLayoutResourcesResourceIdRouteRoute:
    protectedLayoutResourcesResourceIdRouteRoute,
  protectedLayoutLearnIndexRoute: protectedLayoutLearnIndexRoute,
}

const protectedLayoutRouteRouteWithChildren =
  protectedLayoutRouteRoute._addFileChildren(protectedLayoutRouteRouteChildren)

interface ApiLearnAssignmentsAssignmentIdRouteChildren {
  ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute: typeof ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute
  ApiLearnAssignmentsAssignmentIdSubmissionsRoute: typeof ApiLearnAssignmentsAssignmentIdSubmissionsRoute
}

const ApiLearnAssignmentsAssignmentIdRouteChildren: ApiLearnAssignmentsAssignmentIdRouteChildren =
  {
    ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute:
      ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute,
    ApiLearnAssignmentsAssignmentIdSubmissionsRoute:
      ApiLearnAssignmentsAssignmentIdSubmissionsRoute,
  }

const ApiLearnAssignmentsAssignmentIdRouteWithChildren =
  ApiLearnAssignmentsAssignmentIdRoute._addFileChildren(
    ApiLearnAssignmentsAssignmentIdRouteChildren,
  )

interface ApiLearnSubmissionsSubmissionIdRouteChildren {
  ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute: typeof ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute
}

const ApiLearnSubmissionsSubmissionIdRouteChildren: ApiLearnSubmissionsSubmissionIdRouteChildren =
  {
    ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute:
      ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute,
  }

const ApiLearnSubmissionsSubmissionIdRouteWithChildren =
  ApiLearnSubmissionsSubmissionIdRoute._addFileChildren(
    ApiLearnSubmissionsSubmissionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  protectedLayoutRouteRoute: protectedLayoutRouteRouteWithChildren,
  authV2ForgotPasswordRoute: authV2ForgotPasswordRoute,
  authV2MeRoute: authV2MeRoute,
  authV2ResetPasswordRoute: authV2ResetPasswordRoute,
  ApiDashboardActionBannersRoute: ApiDashboardActionBannersRoute,
  ApiDashboardAnnouncementsRoute: ApiDashboardAnnouncementsRoute,
  ApiDashboardBannersRoute: ApiDashboardBannersRoute,
  ApiDashboardPendingTasksRoute: ApiDashboardPendingTasksRoute,
  ApiDashboardProductUpdatesRoute: ApiDashboardProductUpdatesRoute,
  ApiDashboardScheduleRoute: ApiDashboardScheduleRoute,
  ApiLearnBatchDataRoute: ApiLearnBatchDataRoute,
  ApiLearnBatchesRoute: ApiLearnBatchesRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authSigninIndexRoute: authSigninIndexRoute,
  authSwitchAccountIndexRoute: authSwitchAccountIndexRoute,
  protectedZoomIndexRoute: protectedZoomIndexRoute,
  authV2AuthLinkedAccountsRoute: authV2AuthLinkedAccountsRoute,
  authV2AuthUseAccountRoute: authV2AuthUseAccountRoute,
  authV2LoginRequestOtpRoute: authV2LoginRequestOtpRoute,
  authV2LoginVerifyOtpRoute: authV2LoginVerifyOtpRoute,
  ApiLearnAiTutorEndRoute: ApiLearnAiTutorEndRoute,
  ApiLearnAiTutorLimitRoute: ApiLearnAiTutorLimitRoute,
  ApiLearnAssignmentsAssignmentIdRoute:
    ApiLearnAssignmentsAssignmentIdRouteWithChildren,
  ApiLearnLecturesLectureIdRoute: ApiLearnLecturesLectureIdRoute,
  ApiLearnResourcesResourceIdRoute: ApiLearnResourcesResourceIdRoute,
  ApiLearnSubmissionsSubmissionIdRoute:
    ApiLearnSubmissionsSubmissionIdRouteWithChildren,
  authResetPasswordTokenIndexRoute: authResetPasswordTokenIndexRoute,
  authV2LoginIndexRoute: authV2LoginIndexRoute,
  ApiLearnAiChatLectureIdHistoryRoute: ApiLearnAiChatLectureIdHistoryRoute,
  ApiLearnAiChatLectureIdSendRoute: ApiLearnAiChatLectureIdSendRoute,
  ApiLearnAiTutorLectureIdDispatchRoute: ApiLearnAiTutorLectureIdDispatchRoute,
  ApiLearnAiTutorLectureIdFeedbackRoute: ApiLearnAiTutorLectureIdFeedbackRoute,
  ApiLearnAiTutorLectureIdSessionRoute: ApiLearnAiTutorLectureIdSessionRoute,
  ApiLearnAiTutorLectureIdTranscriptRoute:
    ApiLearnAiTutorLectureIdTranscriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
