/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedLayoutRouteRouteImport } from './routes/(protected)/_layout/route'
import { Route as protectedLayoutIndexRouteImport } from './routes/(protected)/_layout/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as protectedLayoutMasaiverseRouteRouteImport } from './routes/(protected)/_layout/masaiverse/route'
import { Route as protectedLayoutMasaiverseIndexRouteImport } from './routes/(protected)/_layout/masaiverse/index'
import { Route as protectedLayoutLearnIndexRouteImport } from './routes/(protected)/_layout/learn/index'
import { Route as protectedLayoutResourcesResourceIdRouteRouteImport } from './routes/(protected)/_layout/resources_/$resourceId/route'
import { Route as protectedLayoutLecturesLectureIdRouteRouteImport } from './routes/(protected)/_layout/lectures_/$lectureId/route'
import { Route as protectedLayoutAssignmentsAssignmentIdRouteRouteImport } from './routes/(protected)/_layout/assignments_/$assignmentId/route'

const protectedLayoutRouteRoute = protectedLayoutRouteRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutIndexRoute = protectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutMasaiverseRouteRoute =
  protectedLayoutMasaiverseRouteRouteImport.update({
    id: '/masaiverse',
    path: '/masaiverse',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutMasaiverseIndexRoute =
  protectedLayoutMasaiverseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedLayoutMasaiverseRouteRoute,
  } as any)
const protectedLayoutLearnIndexRoute =
  protectedLayoutLearnIndexRouteImport.update({
    id: '/learn/',
    path: '/learn/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutResourcesResourceIdRouteRoute =
  protectedLayoutResourcesResourceIdRouteRouteImport.update({
    id: '/resources_/$resourceId',
    path: '/resources/$resourceId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutLecturesLectureIdRouteRoute =
  protectedLayoutLecturesLectureIdRouteRouteImport.update({
    id: '/lectures_/$lectureId',
    path: '/lectures/$lectureId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutAssignmentsAssignmentIdRouteRoute =
  protectedLayoutAssignmentsAssignmentIdRouteRouteImport.update({
    id: '/assignments_/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/masaiverse': typeof protectedLayoutMasaiverseRouteRouteWithChildren
  '/login/': typeof authLoginIndexRoute
  '/': typeof protectedLayoutIndexRoute
  '/assignments/$assignmentId': typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  '/lectures/$lectureId': typeof protectedLayoutLecturesLectureIdRouteRoute
  '/resources/$resourceId': typeof protectedLayoutResourcesResourceIdRouteRoute
  '/learn/': typeof protectedLayoutLearnIndexRoute
  '/masaiverse/': typeof protectedLayoutMasaiverseIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginIndexRoute
  '/': typeof protectedLayoutIndexRoute
  '/assignments/$assignmentId': typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  '/lectures/$lectureId': typeof protectedLayoutLecturesLectureIdRouteRoute
  '/resources/$resourceId': typeof protectedLayoutResourcesResourceIdRouteRoute
  '/learn': typeof protectedLayoutLearnIndexRoute
  '/masaiverse': typeof protectedLayoutMasaiverseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)/_layout': typeof protectedLayoutRouteRouteWithChildren
  '/(protected)/_layout/masaiverse': typeof protectedLayoutMasaiverseRouteRouteWithChildren
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(protected)/_layout/': typeof protectedLayoutIndexRoute
  '/(protected)/_layout/assignments_/$assignmentId': typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  '/(protected)/_layout/lectures_/$lectureId': typeof protectedLayoutLecturesLectureIdRouteRoute
  '/(protected)/_layout/resources_/$resourceId': typeof protectedLayoutResourcesResourceIdRouteRoute
  '/(protected)/_layout/learn/': typeof protectedLayoutLearnIndexRoute
  '/(protected)/_layout/masaiverse/': typeof protectedLayoutMasaiverseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/masaiverse'
    | '/login/'
    | '/'
    | '/assignments/$assignmentId'
    | '/lectures/$lectureId'
    | '/resources/$resourceId'
    | '/learn/'
    | '/masaiverse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/assignments/$assignmentId'
    | '/lectures/$lectureId'
    | '/resources/$resourceId'
    | '/learn'
    | '/masaiverse'
  id:
    | '__root__'
    | '/(protected)/_layout'
    | '/(protected)/_layout/masaiverse'
    | '/(auth)/login/'
    | '/(protected)/_layout/'
    | '/(protected)/_layout/assignments_/$assignmentId'
    | '/(protected)/_layout/lectures_/$lectureId'
    | '/(protected)/_layout/resources_/$resourceId'
    | '/(protected)/_layout/learn/'
    | '/(protected)/_layout/masaiverse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedLayoutRouteRoute: typeof protectedLayoutRouteRouteWithChildren
  authLoginIndexRoute: typeof authLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/': {
      id: '/(protected)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/masaiverse': {
      id: '/(protected)/_layout/masaiverse'
      path: '/masaiverse'
      fullPath: '/masaiverse'
      preLoaderRoute: typeof protectedLayoutMasaiverseRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/masaiverse/': {
      id: '/(protected)/_layout/masaiverse/'
      path: '/'
      fullPath: '/masaiverse/'
      preLoaderRoute: typeof protectedLayoutMasaiverseIndexRouteImport
      parentRoute: typeof protectedLayoutMasaiverseRouteRoute
    }
    '/(protected)/_layout/learn/': {
      id: '/(protected)/_layout/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof protectedLayoutLearnIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/resources_/$resourceId': {
      id: '/(protected)/_layout/resources_/$resourceId'
      path: '/resources/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof protectedLayoutResourcesResourceIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/lectures_/$lectureId': {
      id: '/(protected)/_layout/lectures_/$lectureId'
      path: '/lectures/$lectureId'
      fullPath: '/lectures/$lectureId'
      preLoaderRoute: typeof protectedLayoutLecturesLectureIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/assignments_/$assignmentId': {
      id: '/(protected)/_layout/assignments_/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof protectedLayoutAssignmentsAssignmentIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
  }
}

interface protectedLayoutMasaiverseRouteRouteChildren {
  protectedLayoutMasaiverseIndexRoute: typeof protectedLayoutMasaiverseIndexRoute
}

const protectedLayoutMasaiverseRouteRouteChildren: protectedLayoutMasaiverseRouteRouteChildren =
  {
    protectedLayoutMasaiverseIndexRoute: protectedLayoutMasaiverseIndexRoute,
  }

const protectedLayoutMasaiverseRouteRouteWithChildren =
  protectedLayoutMasaiverseRouteRoute._addFileChildren(
    protectedLayoutMasaiverseRouteRouteChildren,
  )

interface protectedLayoutRouteRouteChildren {
  protectedLayoutMasaiverseRouteRoute: typeof protectedLayoutMasaiverseRouteRouteWithChildren
  protectedLayoutIndexRoute: typeof protectedLayoutIndexRoute
  protectedLayoutAssignmentsAssignmentIdRouteRoute: typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  protectedLayoutLecturesLectureIdRouteRoute: typeof protectedLayoutLecturesLectureIdRouteRoute
  protectedLayoutResourcesResourceIdRouteRoute: typeof protectedLayoutResourcesResourceIdRouteRoute
  protectedLayoutLearnIndexRoute: typeof protectedLayoutLearnIndexRoute
}

const protectedLayoutRouteRouteChildren: protectedLayoutRouteRouteChildren = {
  protectedLayoutMasaiverseRouteRoute:
    protectedLayoutMasaiverseRouteRouteWithChildren,
  protectedLayoutIndexRoute: protectedLayoutIndexRoute,
  protectedLayoutAssignmentsAssignmentIdRouteRoute:
    protectedLayoutAssignmentsAssignmentIdRouteRoute,
  protectedLayoutLecturesLectureIdRouteRoute:
    protectedLayoutLecturesLectureIdRouteRoute,
  protectedLayoutResourcesResourceIdRouteRoute:
    protectedLayoutResourcesResourceIdRouteRoute,
  protectedLayoutLearnIndexRoute: protectedLayoutLearnIndexRoute,
}

const protectedLayoutRouteRouteWithChildren =
  protectedLayoutRouteRoute._addFileChildren(protectedLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  protectedLayoutRouteRoute: protectedLayoutRouteRouteWithChildren,
  authLoginIndexRoute: authLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
