/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedLayoutRouteRouteImport } from './routes/(protected)/_layout/route'
import { Route as protectedLayoutIndexRouteImport } from './routes/(protected)/_layout/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as ApiLearnBatchesRouteImport } from './routes/api/learn/batches'
import { Route as ApiLearnBatchDataRouteImport } from './routes/api/learn/batch-data'
import { Route as ApiDashboardScheduleRouteImport } from './routes/api/dashboard/schedule'
import { Route as ApiDashboardProductUpdatesRouteImport } from './routes/api/dashboard/product-updates'
import { Route as ApiDashboardPendingTasksRouteImport } from './routes/api/dashboard/pending-tasks'
import { Route as ApiDashboardBannersRouteImport } from './routes/api/dashboard/banners'
import { Route as ApiDashboardAnnouncementsRouteImport } from './routes/api/dashboard/announcements'
import { Route as ApiDashboardActionBannersRouteImport } from './routes/api/dashboard/action-banners'
import { Route as protectedLayoutMasaiverseRouteRouteImport } from './routes/(protected)/_layout/masaiverse/route'
import { Route as protectedLayoutMasaiverseIndexRouteImport } from './routes/(protected)/_layout/masaiverse/index'
import { Route as protectedLayoutLearnIndexRouteImport } from './routes/(protected)/_layout/learn/index'
import { Route as ApiLearnSubmissionsSubmissionIdRouteImport } from './routes/api/learn/submissions/$submissionId'
import { Route as ApiLearnResourcesResourceIdRouteImport } from './routes/api/learn/resources/$resourceId'
import { Route as ApiLearnLecturesLectureIdRouteImport } from './routes/api/learn/lectures/$lectureId'
import { Route as ApiLearnAssignmentsAssignmentIdRouteImport } from './routes/api/learn/assignments/$assignmentId'
import { Route as protectedLayoutResourcesResourceIdRouteRouteImport } from './routes/(protected)/_layout/resources_/$resourceId/route'
import { Route as protectedLayoutLecturesLectureIdRouteRouteImport } from './routes/(protected)/_layout/lectures_/$lectureId/route'
import { Route as protectedLayoutAssignmentsAssignmentIdRouteRouteImport } from './routes/(protected)/_layout/assignments_/$assignmentId/route'
import { Route as ApiLearnSubmissionsSubmissionIdViewOnPlatformRouteImport } from './routes/api/learn/submissions/$submissionId/view-on-platform'
import { Route as ApiLearnAssignmentsAssignmentIdSubmissionsRouteImport } from './routes/api/learn/assignments/$assignmentId/submissions'
import { Route as ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRouteImport } from './routes/api/learn/assignments/$assignmentId/assess-platform-url'

const protectedLayoutRouteRoute = protectedLayoutRouteRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutIndexRoute = protectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearnBatchesRoute = ApiLearnBatchesRouteImport.update({
  id: '/api/learn/batches',
  path: '/api/learn/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearnBatchDataRoute = ApiLearnBatchDataRouteImport.update({
  id: '/api/learn/batch-data',
  path: '/api/learn/batch-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardScheduleRoute = ApiDashboardScheduleRouteImport.update({
  id: '/api/dashboard/schedule',
  path: '/api/dashboard/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardProductUpdatesRoute =
  ApiDashboardProductUpdatesRouteImport.update({
    id: '/api/dashboard/product-updates',
    path: '/api/dashboard/product-updates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDashboardPendingTasksRoute =
  ApiDashboardPendingTasksRouteImport.update({
    id: '/api/dashboard/pending-tasks',
    path: '/api/dashboard/pending-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDashboardBannersRoute = ApiDashboardBannersRouteImport.update({
  id: '/api/dashboard/banners',
  path: '/api/dashboard/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardAnnouncementsRoute =
  ApiDashboardAnnouncementsRouteImport.update({
    id: '/api/dashboard/announcements',
    path: '/api/dashboard/announcements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDashboardActionBannersRoute =
  ApiDashboardActionBannersRouteImport.update({
    id: '/api/dashboard/action-banners',
    path: '/api/dashboard/action-banners',
    getParentRoute: () => rootRouteImport,
  } as any)
const protectedLayoutMasaiverseRouteRoute =
  protectedLayoutMasaiverseRouteRouteImport.update({
    id: '/masaiverse',
    path: '/masaiverse',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutMasaiverseIndexRoute =
  protectedLayoutMasaiverseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedLayoutMasaiverseRouteRoute,
  } as any)
const protectedLayoutLearnIndexRoute =
  protectedLayoutLearnIndexRouteImport.update({
    id: '/learn/',
    path: '/learn/',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const ApiLearnSubmissionsSubmissionIdRoute =
  ApiLearnSubmissionsSubmissionIdRouteImport.update({
    id: '/api/learn/submissions/$submissionId',
    path: '/api/learn/submissions/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnResourcesResourceIdRoute =
  ApiLearnResourcesResourceIdRouteImport.update({
    id: '/api/learn/resources/$resourceId',
    path: '/api/learn/resources/$resourceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnLecturesLectureIdRoute =
  ApiLearnLecturesLectureIdRouteImport.update({
    id: '/api/learn/lectures/$lectureId',
    path: '/api/learn/lectures/$lectureId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLearnAssignmentsAssignmentIdRoute =
  ApiLearnAssignmentsAssignmentIdRouteImport.update({
    id: '/api/learn/assignments/$assignmentId',
    path: '/api/learn/assignments/$assignmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const protectedLayoutResourcesResourceIdRouteRoute =
  protectedLayoutResourcesResourceIdRouteRouteImport.update({
    id: '/resources_/$resourceId',
    path: '/resources/$resourceId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutLecturesLectureIdRouteRoute =
  protectedLayoutLecturesLectureIdRouteRouteImport.update({
    id: '/lectures_/$lectureId',
    path: '/lectures/$lectureId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const protectedLayoutAssignmentsAssignmentIdRouteRoute =
  protectedLayoutAssignmentsAssignmentIdRouteRouteImport.update({
    id: '/assignments_/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => protectedLayoutRouteRoute,
  } as any)
const ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute =
  ApiLearnSubmissionsSubmissionIdViewOnPlatformRouteImport.update({
    id: '/view-on-platform',
    path: '/view-on-platform',
    getParentRoute: () => ApiLearnSubmissionsSubmissionIdRoute,
  } as any)
const ApiLearnAssignmentsAssignmentIdSubmissionsRoute =
  ApiLearnAssignmentsAssignmentIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => ApiLearnAssignmentsAssignmentIdRoute,
  } as any)
const ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute =
  ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRouteImport.update({
    id: '/assess-platform-url',
    path: '/assess-platform-url',
    getParentRoute: () => ApiLearnAssignmentsAssignmentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/masaiverse': typeof protectedLayoutMasaiverseRouteRouteWithChildren
  '/api/dashboard/action-banners': typeof ApiDashboardActionBannersRoute
  '/api/dashboard/announcements': typeof ApiDashboardAnnouncementsRoute
  '/api/dashboard/banners': typeof ApiDashboardBannersRoute
  '/api/dashboard/pending-tasks': typeof ApiDashboardPendingTasksRoute
  '/api/dashboard/product-updates': typeof ApiDashboardProductUpdatesRoute
  '/api/dashboard/schedule': typeof ApiDashboardScheduleRoute
  '/api/learn/batch-data': typeof ApiLearnBatchDataRoute
  '/api/learn/batches': typeof ApiLearnBatchesRoute
  '/login/': typeof authLoginIndexRoute
  '/': typeof protectedLayoutIndexRoute
  '/assignments/$assignmentId': typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  '/lectures/$lectureId': typeof protectedLayoutLecturesLectureIdRouteRoute
  '/resources/$resourceId': typeof protectedLayoutResourcesResourceIdRouteRoute
  '/api/learn/assignments/$assignmentId': typeof ApiLearnAssignmentsAssignmentIdRouteWithChildren
  '/api/learn/lectures/$lectureId': typeof ApiLearnLecturesLectureIdRoute
  '/api/learn/resources/$resourceId': typeof ApiLearnResourcesResourceIdRoute
  '/api/learn/submissions/$submissionId': typeof ApiLearnSubmissionsSubmissionIdRouteWithChildren
  '/learn/': typeof protectedLayoutLearnIndexRoute
  '/masaiverse/': typeof protectedLayoutMasaiverseIndexRoute
  '/api/learn/assignments/$assignmentId/assess-platform-url': typeof ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute
  '/api/learn/assignments/$assignmentId/submissions': typeof ApiLearnAssignmentsAssignmentIdSubmissionsRoute
  '/api/learn/submissions/$submissionId/view-on-platform': typeof ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute
}
export interface FileRoutesByTo {
  '/api/dashboard/action-banners': typeof ApiDashboardActionBannersRoute
  '/api/dashboard/announcements': typeof ApiDashboardAnnouncementsRoute
  '/api/dashboard/banners': typeof ApiDashboardBannersRoute
  '/api/dashboard/pending-tasks': typeof ApiDashboardPendingTasksRoute
  '/api/dashboard/product-updates': typeof ApiDashboardProductUpdatesRoute
  '/api/dashboard/schedule': typeof ApiDashboardScheduleRoute
  '/api/learn/batch-data': typeof ApiLearnBatchDataRoute
  '/api/learn/batches': typeof ApiLearnBatchesRoute
  '/login': typeof authLoginIndexRoute
  '/': typeof protectedLayoutIndexRoute
  '/assignments/$assignmentId': typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  '/lectures/$lectureId': typeof protectedLayoutLecturesLectureIdRouteRoute
  '/resources/$resourceId': typeof protectedLayoutResourcesResourceIdRouteRoute
  '/api/learn/assignments/$assignmentId': typeof ApiLearnAssignmentsAssignmentIdRouteWithChildren
  '/api/learn/lectures/$lectureId': typeof ApiLearnLecturesLectureIdRoute
  '/api/learn/resources/$resourceId': typeof ApiLearnResourcesResourceIdRoute
  '/api/learn/submissions/$submissionId': typeof ApiLearnSubmissionsSubmissionIdRouteWithChildren
  '/learn': typeof protectedLayoutLearnIndexRoute
  '/masaiverse': typeof protectedLayoutMasaiverseIndexRoute
  '/api/learn/assignments/$assignmentId/assess-platform-url': typeof ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute
  '/api/learn/assignments/$assignmentId/submissions': typeof ApiLearnAssignmentsAssignmentIdSubmissionsRoute
  '/api/learn/submissions/$submissionId/view-on-platform': typeof ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)/_layout': typeof protectedLayoutRouteRouteWithChildren
  '/(protected)/_layout/masaiverse': typeof protectedLayoutMasaiverseRouteRouteWithChildren
  '/api/dashboard/action-banners': typeof ApiDashboardActionBannersRoute
  '/api/dashboard/announcements': typeof ApiDashboardAnnouncementsRoute
  '/api/dashboard/banners': typeof ApiDashboardBannersRoute
  '/api/dashboard/pending-tasks': typeof ApiDashboardPendingTasksRoute
  '/api/dashboard/product-updates': typeof ApiDashboardProductUpdatesRoute
  '/api/dashboard/schedule': typeof ApiDashboardScheduleRoute
  '/api/learn/batch-data': typeof ApiLearnBatchDataRoute
  '/api/learn/batches': typeof ApiLearnBatchesRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(protected)/_layout/': typeof protectedLayoutIndexRoute
  '/(protected)/_layout/assignments_/$assignmentId': typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  '/(protected)/_layout/lectures_/$lectureId': typeof protectedLayoutLecturesLectureIdRouteRoute
  '/(protected)/_layout/resources_/$resourceId': typeof protectedLayoutResourcesResourceIdRouteRoute
  '/api/learn/assignments/$assignmentId': typeof ApiLearnAssignmentsAssignmentIdRouteWithChildren
  '/api/learn/lectures/$lectureId': typeof ApiLearnLecturesLectureIdRoute
  '/api/learn/resources/$resourceId': typeof ApiLearnResourcesResourceIdRoute
  '/api/learn/submissions/$submissionId': typeof ApiLearnSubmissionsSubmissionIdRouteWithChildren
  '/(protected)/_layout/learn/': typeof protectedLayoutLearnIndexRoute
  '/(protected)/_layout/masaiverse/': typeof protectedLayoutMasaiverseIndexRoute
  '/api/learn/assignments/$assignmentId/assess-platform-url': typeof ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute
  '/api/learn/assignments/$assignmentId/submissions': typeof ApiLearnAssignmentsAssignmentIdSubmissionsRoute
  '/api/learn/submissions/$submissionId/view-on-platform': typeof ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/masaiverse'
    | '/api/dashboard/action-banners'
    | '/api/dashboard/announcements'
    | '/api/dashboard/banners'
    | '/api/dashboard/pending-tasks'
    | '/api/dashboard/product-updates'
    | '/api/dashboard/schedule'
    | '/api/learn/batch-data'
    | '/api/learn/batches'
    | '/login/'
    | '/'
    | '/assignments/$assignmentId'
    | '/lectures/$lectureId'
    | '/resources/$resourceId'
    | '/api/learn/assignments/$assignmentId'
    | '/api/learn/lectures/$lectureId'
    | '/api/learn/resources/$resourceId'
    | '/api/learn/submissions/$submissionId'
    | '/learn/'
    | '/masaiverse/'
    | '/api/learn/assignments/$assignmentId/assess-platform-url'
    | '/api/learn/assignments/$assignmentId/submissions'
    | '/api/learn/submissions/$submissionId/view-on-platform'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/dashboard/action-banners'
    | '/api/dashboard/announcements'
    | '/api/dashboard/banners'
    | '/api/dashboard/pending-tasks'
    | '/api/dashboard/product-updates'
    | '/api/dashboard/schedule'
    | '/api/learn/batch-data'
    | '/api/learn/batches'
    | '/login'
    | '/'
    | '/assignments/$assignmentId'
    | '/lectures/$lectureId'
    | '/resources/$resourceId'
    | '/api/learn/assignments/$assignmentId'
    | '/api/learn/lectures/$lectureId'
    | '/api/learn/resources/$resourceId'
    | '/api/learn/submissions/$submissionId'
    | '/learn'
    | '/masaiverse'
    | '/api/learn/assignments/$assignmentId/assess-platform-url'
    | '/api/learn/assignments/$assignmentId/submissions'
    | '/api/learn/submissions/$submissionId/view-on-platform'
  id:
    | '__root__'
    | '/(protected)/_layout'
    | '/(protected)/_layout/masaiverse'
    | '/api/dashboard/action-banners'
    | '/api/dashboard/announcements'
    | '/api/dashboard/banners'
    | '/api/dashboard/pending-tasks'
    | '/api/dashboard/product-updates'
    | '/api/dashboard/schedule'
    | '/api/learn/batch-data'
    | '/api/learn/batches'
    | '/(auth)/login/'
    | '/(protected)/_layout/'
    | '/(protected)/_layout/assignments_/$assignmentId'
    | '/(protected)/_layout/lectures_/$lectureId'
    | '/(protected)/_layout/resources_/$resourceId'
    | '/api/learn/assignments/$assignmentId'
    | '/api/learn/lectures/$lectureId'
    | '/api/learn/resources/$resourceId'
    | '/api/learn/submissions/$submissionId'
    | '/(protected)/_layout/learn/'
    | '/(protected)/_layout/masaiverse/'
    | '/api/learn/assignments/$assignmentId/assess-platform-url'
    | '/api/learn/assignments/$assignmentId/submissions'
    | '/api/learn/submissions/$submissionId/view-on-platform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedLayoutRouteRoute: typeof protectedLayoutRouteRouteWithChildren
  ApiDashboardActionBannersRoute: typeof ApiDashboardActionBannersRoute
  ApiDashboardAnnouncementsRoute: typeof ApiDashboardAnnouncementsRoute
  ApiDashboardBannersRoute: typeof ApiDashboardBannersRoute
  ApiDashboardPendingTasksRoute: typeof ApiDashboardPendingTasksRoute
  ApiDashboardProductUpdatesRoute: typeof ApiDashboardProductUpdatesRoute
  ApiDashboardScheduleRoute: typeof ApiDashboardScheduleRoute
  ApiLearnBatchDataRoute: typeof ApiLearnBatchDataRoute
  ApiLearnBatchesRoute: typeof ApiLearnBatchesRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  ApiLearnAssignmentsAssignmentIdRoute: typeof ApiLearnAssignmentsAssignmentIdRouteWithChildren
  ApiLearnLecturesLectureIdRoute: typeof ApiLearnLecturesLectureIdRoute
  ApiLearnResourcesResourceIdRoute: typeof ApiLearnResourcesResourceIdRoute
  ApiLearnSubmissionsSubmissionIdRoute: typeof ApiLearnSubmissionsSubmissionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/': {
      id: '/(protected)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedLayoutIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/batches': {
      id: '/api/learn/batches'
      path: '/api/learn/batches'
      fullPath: '/api/learn/batches'
      preLoaderRoute: typeof ApiLearnBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/batch-data': {
      id: '/api/learn/batch-data'
      path: '/api/learn/batch-data'
      fullPath: '/api/learn/batch-data'
      preLoaderRoute: typeof ApiLearnBatchDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/schedule': {
      id: '/api/dashboard/schedule'
      path: '/api/dashboard/schedule'
      fullPath: '/api/dashboard/schedule'
      preLoaderRoute: typeof ApiDashboardScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/product-updates': {
      id: '/api/dashboard/product-updates'
      path: '/api/dashboard/product-updates'
      fullPath: '/api/dashboard/product-updates'
      preLoaderRoute: typeof ApiDashboardProductUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/pending-tasks': {
      id: '/api/dashboard/pending-tasks'
      path: '/api/dashboard/pending-tasks'
      fullPath: '/api/dashboard/pending-tasks'
      preLoaderRoute: typeof ApiDashboardPendingTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/banners': {
      id: '/api/dashboard/banners'
      path: '/api/dashboard/banners'
      fullPath: '/api/dashboard/banners'
      preLoaderRoute: typeof ApiDashboardBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/announcements': {
      id: '/api/dashboard/announcements'
      path: '/api/dashboard/announcements'
      fullPath: '/api/dashboard/announcements'
      preLoaderRoute: typeof ApiDashboardAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/action-banners': {
      id: '/api/dashboard/action-banners'
      path: '/api/dashboard/action-banners'
      fullPath: '/api/dashboard/action-banners'
      preLoaderRoute: typeof ApiDashboardActionBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/masaiverse': {
      id: '/(protected)/_layout/masaiverse'
      path: '/masaiverse'
      fullPath: '/masaiverse'
      preLoaderRoute: typeof protectedLayoutMasaiverseRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/masaiverse/': {
      id: '/(protected)/_layout/masaiverse/'
      path: '/'
      fullPath: '/masaiverse/'
      preLoaderRoute: typeof protectedLayoutMasaiverseIndexRouteImport
      parentRoute: typeof protectedLayoutMasaiverseRouteRoute
    }
    '/(protected)/_layout/learn/': {
      id: '/(protected)/_layout/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof protectedLayoutLearnIndexRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/api/learn/submissions/$submissionId': {
      id: '/api/learn/submissions/$submissionId'
      path: '/api/learn/submissions/$submissionId'
      fullPath: '/api/learn/submissions/$submissionId'
      preLoaderRoute: typeof ApiLearnSubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/resources/$resourceId': {
      id: '/api/learn/resources/$resourceId'
      path: '/api/learn/resources/$resourceId'
      fullPath: '/api/learn/resources/$resourceId'
      preLoaderRoute: typeof ApiLearnResourcesResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/lectures/$lectureId': {
      id: '/api/learn/lectures/$lectureId'
      path: '/api/learn/lectures/$lectureId'
      fullPath: '/api/learn/lectures/$lectureId'
      preLoaderRoute: typeof ApiLearnLecturesLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learn/assignments/$assignmentId': {
      id: '/api/learn/assignments/$assignmentId'
      path: '/api/learn/assignments/$assignmentId'
      fullPath: '/api/learn/assignments/$assignmentId'
      preLoaderRoute: typeof ApiLearnAssignmentsAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/resources_/$resourceId': {
      id: '/(protected)/_layout/resources_/$resourceId'
      path: '/resources/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof protectedLayoutResourcesResourceIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/lectures_/$lectureId': {
      id: '/(protected)/_layout/lectures_/$lectureId'
      path: '/lectures/$lectureId'
      fullPath: '/lectures/$lectureId'
      preLoaderRoute: typeof protectedLayoutLecturesLectureIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/(protected)/_layout/assignments_/$assignmentId': {
      id: '/(protected)/_layout/assignments_/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof protectedLayoutAssignmentsAssignmentIdRouteRouteImport
      parentRoute: typeof protectedLayoutRouteRoute
    }
    '/api/learn/submissions/$submissionId/view-on-platform': {
      id: '/api/learn/submissions/$submissionId/view-on-platform'
      path: '/view-on-platform'
      fullPath: '/api/learn/submissions/$submissionId/view-on-platform'
      preLoaderRoute: typeof ApiLearnSubmissionsSubmissionIdViewOnPlatformRouteImport
      parentRoute: typeof ApiLearnSubmissionsSubmissionIdRoute
    }
    '/api/learn/assignments/$assignmentId/submissions': {
      id: '/api/learn/assignments/$assignmentId/submissions'
      path: '/submissions'
      fullPath: '/api/learn/assignments/$assignmentId/submissions'
      preLoaderRoute: typeof ApiLearnAssignmentsAssignmentIdSubmissionsRouteImport
      parentRoute: typeof ApiLearnAssignmentsAssignmentIdRoute
    }
    '/api/learn/assignments/$assignmentId/assess-platform-url': {
      id: '/api/learn/assignments/$assignmentId/assess-platform-url'
      path: '/assess-platform-url'
      fullPath: '/api/learn/assignments/$assignmentId/assess-platform-url'
      preLoaderRoute: typeof ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRouteImport
      parentRoute: typeof ApiLearnAssignmentsAssignmentIdRoute
    }
  }
}

interface protectedLayoutMasaiverseRouteRouteChildren {
  protectedLayoutMasaiverseIndexRoute: typeof protectedLayoutMasaiverseIndexRoute
}

const protectedLayoutMasaiverseRouteRouteChildren: protectedLayoutMasaiverseRouteRouteChildren =
  {
    protectedLayoutMasaiverseIndexRoute: protectedLayoutMasaiverseIndexRoute,
  }

const protectedLayoutMasaiverseRouteRouteWithChildren =
  protectedLayoutMasaiverseRouteRoute._addFileChildren(
    protectedLayoutMasaiverseRouteRouteChildren,
  )

interface protectedLayoutRouteRouteChildren {
  protectedLayoutMasaiverseRouteRoute: typeof protectedLayoutMasaiverseRouteRouteWithChildren
  protectedLayoutIndexRoute: typeof protectedLayoutIndexRoute
  protectedLayoutAssignmentsAssignmentIdRouteRoute: typeof protectedLayoutAssignmentsAssignmentIdRouteRoute
  protectedLayoutLecturesLectureIdRouteRoute: typeof protectedLayoutLecturesLectureIdRouteRoute
  protectedLayoutResourcesResourceIdRouteRoute: typeof protectedLayoutResourcesResourceIdRouteRoute
  protectedLayoutLearnIndexRoute: typeof protectedLayoutLearnIndexRoute
}

const protectedLayoutRouteRouteChildren: protectedLayoutRouteRouteChildren = {
  protectedLayoutMasaiverseRouteRoute:
    protectedLayoutMasaiverseRouteRouteWithChildren,
  protectedLayoutIndexRoute: protectedLayoutIndexRoute,
  protectedLayoutAssignmentsAssignmentIdRouteRoute:
    protectedLayoutAssignmentsAssignmentIdRouteRoute,
  protectedLayoutLecturesLectureIdRouteRoute:
    protectedLayoutLecturesLectureIdRouteRoute,
  protectedLayoutResourcesResourceIdRouteRoute:
    protectedLayoutResourcesResourceIdRouteRoute,
  protectedLayoutLearnIndexRoute: protectedLayoutLearnIndexRoute,
}

const protectedLayoutRouteRouteWithChildren =
  protectedLayoutRouteRoute._addFileChildren(protectedLayoutRouteRouteChildren)

interface ApiLearnAssignmentsAssignmentIdRouteChildren {
  ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute: typeof ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute
  ApiLearnAssignmentsAssignmentIdSubmissionsRoute: typeof ApiLearnAssignmentsAssignmentIdSubmissionsRoute
}

const ApiLearnAssignmentsAssignmentIdRouteChildren: ApiLearnAssignmentsAssignmentIdRouteChildren =
  {
    ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute:
      ApiLearnAssignmentsAssignmentIdAssessPlatformUrlRoute,
    ApiLearnAssignmentsAssignmentIdSubmissionsRoute:
      ApiLearnAssignmentsAssignmentIdSubmissionsRoute,
  }

const ApiLearnAssignmentsAssignmentIdRouteWithChildren =
  ApiLearnAssignmentsAssignmentIdRoute._addFileChildren(
    ApiLearnAssignmentsAssignmentIdRouteChildren,
  )

interface ApiLearnSubmissionsSubmissionIdRouteChildren {
  ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute: typeof ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute
}

const ApiLearnSubmissionsSubmissionIdRouteChildren: ApiLearnSubmissionsSubmissionIdRouteChildren =
  {
    ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute:
      ApiLearnSubmissionsSubmissionIdViewOnPlatformRoute,
  }

const ApiLearnSubmissionsSubmissionIdRouteWithChildren =
  ApiLearnSubmissionsSubmissionIdRoute._addFileChildren(
    ApiLearnSubmissionsSubmissionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  protectedLayoutRouteRoute: protectedLayoutRouteRouteWithChildren,
  ApiDashboardActionBannersRoute: ApiDashboardActionBannersRoute,
  ApiDashboardAnnouncementsRoute: ApiDashboardAnnouncementsRoute,
  ApiDashboardBannersRoute: ApiDashboardBannersRoute,
  ApiDashboardPendingTasksRoute: ApiDashboardPendingTasksRoute,
  ApiDashboardProductUpdatesRoute: ApiDashboardProductUpdatesRoute,
  ApiDashboardScheduleRoute: ApiDashboardScheduleRoute,
  ApiLearnBatchDataRoute: ApiLearnBatchDataRoute,
  ApiLearnBatchesRoute: ApiLearnBatchesRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  ApiLearnAssignmentsAssignmentIdRoute:
    ApiLearnAssignmentsAssignmentIdRouteWithChildren,
  ApiLearnLecturesLectureIdRoute: ApiLearnLecturesLectureIdRoute,
  ApiLearnResourcesResourceIdRoute: ApiLearnResourcesResourceIdRoute,
  ApiLearnSubmissionsSubmissionIdRoute:
    ApiLearnSubmissionsSubmissionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
